### ISSUE TITLE
Using bap with raw loader and --raw-base flag

### ISSUE THREAD

**Issue by icemonster** [BinaryAnalysisPlatform/bap#1040]
Hi, I have a program (shown below) that when compiled makes `bap a.out -dbil.adt --loader=raw --raw-base 0x555555504000` terminate with no output. I'm using --raw-base as a way of shifting the base of the binary to a specific address (so I can analyse PIE binaries as if the user code was always loaded with the same base). Am I using the flag wrong? Should I use something else to indicate the base address? Is this a bug?

```
extern void exit (int);
extern void abort (void);

static int i;

int
main (void)
{
  i = -1;
  switch ((signed char) i) {
  case 255:
    abort ();
  default:
    exit (0);
  }
}
```

**Comment by ivg** [comment]
The `raw-base` is the address of the first byte, where the first byte is located at `raw-offset`, for example, to disassemble a function at offset `0x76b` with the address `0x40076b` we cat specify the following parameters (using the corresponding binary to our testsuite):
```
 bap testsuite/bin/x86_64-linux-gnu-echo --loader=raw \
       --raw-{base=0x40076b,offset=0x76b,length=542}
```

(You can omit the length, it will then disassemble beyond the limits of the function). 

Also, speaking of the original problem, PIE binaries will be loaded from the same address anyway. At least on modern platforms. PIE is achieved via jump slots indirections, not via using different base addresses.

**Comment by icemonster** [comment]
I'm not entirely sure why would that make bap silent when executing my original command then. Shouldn't it output bil code where the first byte starts with 0x555555504000 (so every instruction is moved 0x555555504000 bytes)? It works fine without the raw-base flag

**Comment by ivg** [comment]
That's a completely different question :) the output was empty because there was no valid program at the specified location. The culprit here is not the base (it doesn't really affect anything, especially in a PIE binary where all references are PC based), but the `--loader=raw` option, which disables any other loaders (like llvm, elf, ida, etc) thus denying bap to any information about the symbols in the binary. Once you set the `--loader=raw` you mandate that you're the only source of information. Since you didn't specify the starting offset it starts disassembling with the first byte. Assuming that it is an ELF binary (just for the sake of an example, the explanation will generally work for any other inputs), the first three bytes are `7f 45 4c 46` where the last three bytes is `ELF` and together these four bytes stand for the magic header of the ELF files. Surprisingly , `7f 45`  is a valid instruction in x86-64 (which is the default arch for the raw-loader unless you specify a different one). It stands for 
```
$ bap mc '7f 45' --show-{insn=asm,bil} --no-ida
jg 0x45
{
  if (~(ZF | (SF | OF) & ~(SF & OF))) {
    jmp 0x47
  }
}
```

So it is a good start, BAP's speculative disassembler than proceeds forward. Trying to build a CFG in which each path may not halt the CPU, which stands for our definition of a valid program. In other words, if from the given entry point we are able to build a program so that there exists a path that will not halt a CPU (by reaching an invalid instruction) then it is a valid program (i.e., from our prespective, something that an adversary could use). In our case, the disassembler explored all paths that are reachable from `\x7fEL` instruction (including the jump to offset `0x47` and the fall to offset `3`, which is `F...` (and is immediatelly invalid) and proved that all paths unconditionally terminate in an invalid instruction. Therefore, this program could not be executed (in other words executing whatever chunks that we have discovered won't have any observable side effects), so it rules out this binary.

In general, you can control the speculative disassembler behavior, but not from the command line right now. Besides, if you don't need to build a valid control flow graph of a program, and just want to explore your binary, then instead of the `disassemble` command (which is the default command), you can explore the `mc` and `objdump` family of commands. They are nearly identical, except that `mc` lets you type programs in ascii encodings, e.g., `7f 45` or even `\x7fELF`:
```
bap mc '\x7fELF' --show-{insn=asm,bil} 
jg 0x45
{
  if (~(ZF | (SF | OF) & ~(SF & OF))) {
    jmp 0x47
  }
}
the last byte wasn't disassembled
```
while `bap objdump` will work with binaries, which is applicable in your case, e.g., using your initial specification, but with `objdump` instead of `disassemble` we get

```
$ bap objdump input --loader=raw --raw-base 0x555555504000 --show-{insn=asm,bil,invalid,size} | head 
0x2
jg 0x45
{
  if (~(ZF | (SF | OF) & ~(SF & OF))) {
    jmp 0x555555504047
  }
}
<invalid>
0x2
addb (%rcx), %al
```

**Comment by icemonster** [comment]
Ahhh I see! 
The --loader=raw argument just takes the ELF as if everything in the file was instructions, I thought it was able to guess the structure. Well then, it should be a matter of finding the offset at which .init section starts and pass it as --raw-offset and everything should work as I expect it to.

I've done a few experiments and things seem to be working fine with that method. 

Thank you so much for your help and explanation, I think this issue can be closed.

**Comment by ivg** [comment]
Oops, forgot to tell that you can specify the base address in llvm, with `bap --llvm-base 0xAAAAA`
