### ISSUE TITLE
Expose git commit ID if available

### ISSUE THREAD

**Issue by mjambon** [BinaryAnalysisPlatform/bap#1041]
For those using a development version of bap, it would be useful for the application to log the exact version of bap being used. This could be something like: `Bap_main_config.dev_version` where the form of `dev_version` is unspecified, but really is something like `387ab80`, or `387ab80-unclean` if `git status` reports changes.

**Comment by ivg** [comment]
The main problem with this is that those git commits/versions/etc are usually inserted into a program when it is distributed in the binary (or otherwise compiled/build form). In our case, installing from opam is still a from source compilation, so every compilation produces a new build artifact each time. 

So  far, the closest thing I was able to find is `opam var PKG:build-id` and `PKG:hash`. The former gives us "a hash identifying the precise package version with all its dependencies" and would be probably too hard to track this back to the git commit (but we can still record this in the binary for build reproducibility). The latter looks more interesting, but I am not sure what it will return if the package that is being installed is not having an archive (i.e., when it is installed from the git source).

**Comment by ivg** [comment]
Ok, after a deeper look, those variables are of no use fo us :(
The `build-id` [doesn't work][1] for the dev packages (i.e., for packages that do not have archives and checksum fields). And `hash` is also [empty][2] for dev packages, as they don't have the archive file. 

The only idea that is left would be to add a githook that will create a file with the commit id (or pr name or whatever we find useful), whenever master is updated and use this file in the configure script to record the build-id of bap.

[1]: https://github.com/ocaml/opam/blob/d6e4e4acb2a13e010631d9f27c638072030fd93d/src/state/opamPackageVar.ml#L178-L180
[2]: https://github.com/ocaml/opam/blob/d6e4e4acb2a13e010631d9f27c638072030fd93d/src/state/opamPackageVar.ml#L293-L302

**Comment by mjambon** [comment]
Thanks for looking into this.

I'm not following why you think the following wouldn't work: calling `git rev-parse --short=7 HEAD` from the `configure` script, which would put the result into an ml file as a string or string option. I was wondering if it was due to `.git` being removed by opam, but it's there, so the git command to extract the commit ID will work.

For reference, here's what I tried: https://github.com/mjambon/test-repo
I used the opam file which I put in its own local opam repository, then added with `opam repo add NAME PATH`, followed by `opam update` and `opam install test-repo`.

**Comment by ivg** [comment]
Great! I was under impression that .git is not available, when we install from opam, but indeed, this would be the easiest solution.

**Comment by ivg** [comment]
@gitoleg, can you please take this issue from here? The plan is simple:
1. add a new OASIS variable `build-id` to the bap_main library 
2. add it to the bap_main_config.ml.ab
3. in bap_main.ml append it to the version string
4. update our testing branch of opam-repository so that the build-id is initialized to `git rev-parse --short=7 HEAD`

The end result should be a valid [semver][1] (semantic version string), e.g.,
```
2.1.0-alpha+06a2534
```

[1]: https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions
