### ISSUE TITLE
move the spectre detection plugin to bap

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#1077]
We need to open source and move the spectre detection plugin to the BinaryAnalysisPlatform organization from its [original private repository][1] and upgrade it to the latest version of BAP. I think that bap-toolkit is the right place for it.

[1]: https://gitlab.com/igoto/spectre-detector/

**Comment by pluviophilee** [comment]
Hi, I want to know which version of bap is suitable for the spectre detection plugin?

**Comment by ivg** [comment]
The version that I've linked should work with BAP 2.0. Once we will merge that repository here, we will continue developing it. It contains only the static analysis to detect weak code patterns. 

The bundle that was associated with the paper is available [here][1], it also includes the rest part of the functionality mentioned in the paper, like the automatic code correction, etc. It is the snapshot frozen in time, which is no longer developed or maintained. It uses BAP 1.5.0 and OCaml 4.05.0. 

[1]: https://github.com/winter2020/oo7

**Comment by pluviophilee** [comment]
I have try the new version of spectre detection plugin with bap 2.0. But it triggered some errors as follow:

caius@caius-VirtualBox:~/spectre-detector$ make
make -C ddtbd
make[1]: Entering directory '/home/caius/spectre-detector/ddtbd'
bapbuild -pkgs bap-primus,bap-taint ddtbd.plugin
+ ocamlfind ocamlc -c -g -short-paths -thread -package bap-taint -package bap-primus -package ppx_jane -package core_kernel -package bap -pp 'ppx-jane -dump-ast -inline-test-drop' -predicates custom_ppx -predicates ppxlib -o ddtbd.cmo ddtbd.ml
File "ddtbd.ml", line 647, characters 37-44:
Error: This expression has type [ `Tuple of Primus.Lisp.Type.t list ]
       but an expression was expected of type Primus.Lisp.Type.parameters
       The first variant type does not allow tag(s) `All, `Gen
Command exited with code 2.
Compilation unsuccessful after building 2 targets (0 cached) in 00:00:02.
Makefile:4: recipe for target 'ddtbd.plugin' failed
make[1]: *** [ddtbd.plugin] Error 10
make[1]: Leaving directory '/home/caius/spectre-detector/ddtbd'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

Did I miss something important?

**Comment by ivg** [comment]
Nope, it looks like that I've accidentally pulled the dependency on 2.1.0.
I've updated the ddtbd plugin source code to make it work with older
versions of BAP.

**Comment by pluviophilee** [comment]
Nice. Thanks a lot.

**Comment by pluviophilee** [comment]
When running the ddtbd plugin with cmd $bap ./gromacs_base.x86_64 --recipe=check, it triggered warning that it cannot recognize the opcode.I have checked the log file and found that bap cannot recognize SSE instruction, But I remember the release says SSE instruction is available in BAP v2.0.0.  The log file:

x86.warning> the legacy lifter failed at 493307: f3 0f 58 c2    addss   %xmm2, %xmm0 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 58")
x86.warning> failed to lift 493307: f3 0f 58 c2         addss   %xmm2, %xmm0 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 58")
x86.warning> the legacy lifter failed at 49343a: f3 0f 5c c8    subss   %xmm0, %xmm1 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 5c")
x86.warning> failed to lift 49343a: f3 0f 5c c8         subss   %xmm0, %xmm1 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 5c")
x86.warning> the legacy lifter failed at 493446: 0f 54 ca       andps   %xmm2, %xmm1 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 54")
x86.warning> failed to lift 493446: 0f 54 ca    andps   %xmm2, %xmm1 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 54")
x86.warning> the legacy lifter failed at 493449: f3 0f 5a c9    cvtss2sd        %xmm1, %xmm1 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 5a")
x86.warning> failed to lift 493449: f3 0f 5a c9         cvtss2sd        %xmm1, %xmm1 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 5a")
x86.warning> the legacy lifter failed at 493455: 66 0f 2e d1    ucomisd %xmm1, %xmm2 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 2e")

Do you have any idea?

**Comment by ivg** [comment]
That's expected, not all SSE instructions are supported and n a sense that we don't know their precise semantics. But the are still disassembled.

**Comment by pluviophilee** [comment]
ok. Got it.

**Comment by pluviophilee** [comment]
Hi, I have run SPEC2006 based on the spectre detection tool these days. However, it occurs binop error while running several cases, such as gobmk, sjeng, hmmer. I remember you have already done the SPECint experiment in oo7 paper. I guess that I have used the unsuitable configuration. Now I compile the spec file with only -g -O2. And my gcc and g++ version is 5.4.0. Have you ever met this error before? or Could you please share the compile configuration?

**Comment by ivg** [comment]
Can you please show the actual error?

**Comment by pluviophilee** [comment]
Sorry for replying late. The log file for gobmk is as below:
x86.warning> failed to lift 48b850: f3 0f 5c c8  	subss	%xmm0, %xmm1 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 5c")
x86.warning> the legacy lifter failed at 48b862: f3 0f 5c c1  	subss	%xmm1, %xmm0 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 5c")
x86.warning> failed to lift 48b862: f3 0f 5c c1  	subss	%xmm1, %xmm0 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 5c")
x86.warning> the legacy lifter failed at 48b862: f3 0f 5c c1  	subss	%xmm1, %xmm0 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 5c")
x86.warning> failed to lift 48b862: f3 0f 5c c1  	subss	%xmm1, %xmm0 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 5c")
x86.warning> the legacy lifter failed at 48b866: f3 0f 59 40 0c  	mulss	0xc(%rax), %xmm0 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 59")
x86.warning> failed to lift 48b866: f3 0f 59 40 0c  	mulss	0xc(%rax), %xmm0 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 59")
x86.warning> the legacy lifter failed at 48b866: f3 0f 59 40 0c  	mulss	0xc(%rax), %xmm0 - (plugins/x86/x86_utils.ml.Arch_exception x86_64
 "disasm x86: unimplemented feature: unuspported opcode: 0f 59")

.......

run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 340 from 338
primus-greedy.info> killing previous machine 338
ddtbd.warning> ignoring jumping at pos %0005e6f4
primus-limit.info> terminating machine 340 because a maximum number of expressions has been reached
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 341 from 340
primus-greedy.info> killing previous machine 340
ddtbd.warning> ignoring jumping at pos %0005e6f5
run.info> execution from 00000bdc terminated with: primus runtime error - "stack check failed" 
primus-greedy.info> switch to machine 342 from 341
primus-greedy.info> killing previous machine 341
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 339 from 342
primus-greedy.info> killing previous machine 342
ddtbd.warning> ignoring jumping at pos %0005e6cb
primus-lisp.info> skipping a jump to an unknown destination at 0x4010F0
primus-limit.info> terminating machine 339 because a maximum number of expressions has been reached
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 337 from 339
primus-greedy.info> killing previous machine 339
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 336 from 337
primus-greedy.info> killing previous machine 337
ddtbd.warning> ignoring jumping at pos %0005e693
primus-lisp.info> skipping a jump to an unknown destination at 0x401290
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 344 from 336
primus-greedy.info> killing previous machine 336
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 343 from 344
primus-greedy.info> killing previous machine 344
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 335 from 343
primus-greedy.info> killing previous machine 343
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 334 from 335
primus-greedy.info> killing previous machine 335
ddtbd.warning> ignoring jumping at pos %0005e67d
ddtbd.warning> ignoring jumping at pos %0005e6bc
primus-lisp.info> skipping a jump to an unknown destination at 0x456B36
ddtbd.warning> ignoring jumping at pos %0007c9d7
primus-limit.info> terminating machine 334 because a maximum number of expressions has been reached
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 333 from 334
primus-greedy.info> killing previous machine 334
ddtbd.warning> ignoring jumping at pos %0005e66e
ddtbd.warning> ignoring jumping at pos %0005e6bc
primus-lisp.info> skipping a jump to an unknown destination at 0x456B36
ddtbd.warning> ignoring jumping at pos %0007c9d7
primus-limit.info> terminating machine 333 because a maximum number of expressions has been reached
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 332 from 333
primus-greedy.info> killing previous machine 333
ddtbd.warning> ignoring jumping at pos %0005e651
ddtbd.warning> ignoring jumping at pos %00078fe2
ddtbd.warning> ignoring jumping at pos %0005e66f
ddtbd.warning> ignoring jumping at pos %0005e67e
primus-limit.info> terminating machine 332 because a maximum number of expressions has been reached
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 347 from 332
primus-greedy.info> killing previous machine 332
run.info> execution from 00000bdc terminated with: Halt 
primus-greedy.info> switch to machine 346 from 347
primus-greedy.info> killing previous machine 347
ddtbd.warning> ignoring jumping at pos %00078fe3
bap.error> Pass `run' failed at runtime with binop type error - 0:1u + 7:64u
Backtrace:
Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "lib/bap_types/bap_helpers.ml", line 133, characters 9-138
Called from file "lib/bap_primus/bap_primus_interpreter.ml", line 271, characters 12-48
Called from file "lib/monads/monads_monad.ml", line 1402, characters 30-35
Called from file "lib/monads/monads_monad.ml", line 984, characters 60-63
Called from file "lib/monads/monads_monad.ml" (inlined), line 979, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 994, characters 21-27
Called from file "lib/monads/monads_monad.ml", line 1208, characters 37-59
Called from file "lib/bap_primus/bap_primus_machine.ml", line 272, characters 8-198
Called from file "plugins/run/run_main.ml", line 171, characters 2-56
Called from file "lib/bap/bap_project.ml", line 477, characters 20-32
Re-raised at file "lib/bap/bap_project.ml", line 482, characters 6-15
Called from file "lib/bap/bap_project.ml", line 518, characters 4-20
Called from file "lib/bap/bap_project.ml", line 529, characters 10-24

**Comment by pluviophilee** [comment]
I have fixed the previous error. But the program will pause for a while and  occur OOM error when running SPEC2006. The error message is as following:

~/CPU2006v1.0.1/benchspec/CPU2006/473.astar/run/run_base_ref_x86_64.0011 $ bap astar_base.x86_64 --recipe=spectre

[00:00:00]  disassemble: 100% (3/3)
[00:03:25]  primus-greedy:  57% (58/101)
[00:12:32]   limit max path length:  87% (3568/4096)
[00:03:41]  primus-mark-visited:   8% (168/2096)
Fatal error: out of memory.

Have you met this before?

**Comment by ivg** [comment]
I met, but usually this happens after hours of work. But how many gigabytes of RAM do you have? Or more importantly, how many is bap using? You can use `/usr/bin/time -v` to get this information in a readable form, e.g., `/usr/bin/time -v bap ...`

I suspect that the culprit is the memory allocation that we model to precisely. @gitoleg, what is the state of transition of this recipe to the toolkit? Also, when you will be transferring it, make sure that we have the limit-malloc enabled (probably, we shall move the limit-malloc feature into the main repo, if it is not there yet).

**Comment by pluviophilee** [comment]
Yes, I will upload the binary file later.

**Comment by pluviophilee** [comment]
Here is the file
[astar_base.x86_64.zip](https://github.com/BinaryAnalysisPlatform/bap/files/4619587/astar_base.x86_64.zip)
 
and the result of /usr/bin/time command is as following:
 ~/CPU2006v1.0.1/benchspec/CPU2006/473.astar/run/run_base_ref_x86_64.0011$ /usr/bin/time -v bap astar_base.x86_64 --recipe=spectre

[00:00:00]  cache: done
[00:00:00]  disassemble: 100% (3/3)
[00:03:17]  primus-greedy:  57% (58/101)
[00:14:18]   limit max path length:  87% (3568/4096)
[00:03:31]  primus-mark-visited:   8% (168/2096)
Fatal error: out of memory.
Command exited with non-zero status 2
	Command being timed: "bap astar_base.x86_64 --recipe=spectre"
	User time (seconds): 1113.61
	System time (seconds): 4.41
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 18:46.19
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 14282288
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 298
	Minor (reclaiming a frame) page faults: 3641244
	Voluntary context switches: 884
	Involuntary context switches: 8723
	Swaps: 0
	File system inputs: 124056
	File system outputs: 82344
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 2

**Comment by ivg** [comment]
@gitoleg, can you please take a look on what is going on there?

**Comment by gitoleg** [comment]
@ivg sure

**Comment by pluviophilee** [comment]
I have tried to modify the limit_malloc.lisp file, but it still not working.

**Comment by ivg** [comment]
Looks like that this issue has stalled and diverged from the original topic. The analysis was moved to bap-toolkit long time ago, so we can close this issue.

@pluviophilee if you still have problems, please open a new issue, I will look into it.
