### ISSUE TITLE
BAP is slow and overflow error for mach-o binaries 

### ISSUE THREAD

**Issue by sami2316** [BinaryAnalysisPlatform/bap#1103]
I am trying to run `BAP` for MAC kernel binaries (mach-o format with ~14MB size). But I am getting the following error after half an hour of execution. 
```sh
# bap -d --symbolizer=objdump --rooter=internal kernel 
Failed to create a project: Sexp
Z.Overflow

Backtrace:
Raised at file "src/error.ml" (inlined), line 9, characters 14-30
Called from file "src/or_error.ml", line 74, characters 17-32
Called from file "lib/bap_disasm/bap_disasm_basic.ml", line 398, characters 13-40
Called from file "lib/bap_disasm/bap_disasm_basic.ml", line 475, characters 2-28
Called from file "lib/bap_disasm/bap_disasm_rec.ml", line 250, characters 2-220
Called from file "lib/bap_disasm/bap_disasm_rec.ml", line 447, characters 6-44
Called from file "lib/bap_disasm/bap_disasm_basic.ml", line 508, characters 2-7
Called from file "lib/bap_disasm/bap_disasm.ml", line 77, characters 4-47
Called from file "lib/bap_disasm/bap_disasm.ml" (inlined), line 100, characters 6-48
Called from file "lib/bap/bap_project.ml", line 277, characters 10-68
Called from file "lib/bap/bap_project.ml", line 283, characters 42-51
Called from file "src/sequence.ml", line 131, characters 27-34
Called from file "lib/bap/bap_project.ml", line 281, characters 6-139
Called from file "lib/bap/bap_project.ml", line 285, characters 20-34
Called from file "src/or_error.ml", line 66, characters 9-15

``` 
`BAP` version `v1.5.0` and `v1.6.0` on Ubuntu 18 output the above error. But version `v1.4.0` and `v2.0.0` explode the memory as mentioned in [#936](https://github.com/BinaryAnalysisPlatform/bap/issues/936) and BAP is killed by kernel. 

Note: I have tested other large binaries (`non` mach-o) and they work fine with `v1.5.0`. See the attachment for the tested target file. 
[target.zip](https://github.com/BinaryAnalysisPlatform/bap/files/4661458/target.zip)

**Comment by ivg** [comment]
The overflow bug is indeed fixed in 2.0.0 (after we have moved to the new bitvectors). Concerning the speed and memory footprint, it takes about an hour on @gitoleg machine to disassemble it and 23Gb of the resident memory. Looks like this is just a very complex binary (probably highly optimized) and since it is a kernel it uses very large addresses which take more memory to store (in BAP we have an optimization that small bitvectors are stored as immediates, and we switch to a boxed representation only when a bitvector doesn't fit into the native integer. It looks like that in this binary all addresses are large and all computations on them are also producing large binaries, which increases the pressure on the garbage collector and requires more memory to store the information about the binary).

**Comment by ivg** [comment]
I am closing this right now but we will keep this issue in mind, maybe in 2.2.0, we can do better. Thanks for reporting it.

**Comment by ivg** [comment]
Also, it looks like that a lot of time was spent in the caching, so it should run much faster in 2.1.0 with #1090. In addition, you can disable caching with `--no-cache` if you don't need it.
