### ISSUE TITLE
Consider the switch to `ocamlformat` instead of `ocp-indent`.

### ISSUE THREAD

**Issue by XVilka** [BinaryAnalysisPlatform/bap#1149]
Modern OCaml ecosystem works on improving development tools, including indentation checkers/fixers. [Ocamlformat](https://github.com/ocaml-ppx/ocamlformat) is the most modern way to do this. Also it integrates with `dune fmt` seamlessly (assuming [BAP will switch](https://github.com/BinaryAnalysisPlatform/bap/issues/917) to [Dune](https://dune.build) some time in the future). Moreover, it [aims to be compatible with ocp-indent](https://github.com/ocaml-ppx/ocamlformat/issues/476).

**Comment by ivg** [comment]
The main problem is that it will [destroy the history][1] (unless we will solve an NP problem and find a set of configuration flags that will minimize the change). The history is extremely important for us for maintenance so this cosmetic change will cost us a lot of work hours later (as we will spend more time tracking bugs).

Another reason against is that personally, I find the default formatting style disgusting and it doesn't meet with our coding standards. Yes, this could be tuned with options, but it contradicts the [idea of ocamlformat][2] that there should be just _a_ style no matter how it looks like. So it will become a constant battle between readability and style as a fruitless battle since those two should be on the same side. 

In addition, ocamlformat failed to reformat a lot of files and produced several tons of warnings, so it is clearly not ready for use. 

[1]: https://github.com/BinaryAnalysisPlatform/bap/compare/master...ivg:ocamlformatted-bap
[2]: https://github.com/janestreet/ocamlformat#code-style
