### ISSUE TITLE
JIT compilation for Primus/Core Theory?

### ISSUE THREAD

**Issue by XVilka** [BinaryAnalysisPlatform/bap#1150]
Since LLVM is the core BAP dependency, why not to use it for implementing JIT compilation for the Primus and/or Core Theory as well?

```ocaml
(* Create the JIT. *)
let the_execution_engine = ExecutionEngine.create Codegen.the_module in
let the_fpm = PassManager.create_function Codegen.the_module in

(* Set up the optimizer pipeline.  Start with registering info about how the
 * target lays out data structures. *)
DataLayout.add (ExecutionEngine.target_data the_execution_engine) the_fpm;

(* Do simple "peephole" optimizations and bit-twiddling optzn. *)
add_instruction_combining the_fpm;

(* reassociate expressions. *)
add_reassociation the_fpm;

(* Eliminate Common SubExpressions. *)
add_gvn the_fpm;

(* Simplify the control flow graph (deleting unreachable blocks, etc). *)
add_cfg_simplification the_fpm;

ignore (PassManager.initialize the_fpm);

(* Run the main "interpreter loop" now. *)
Toplevel.main_loop the_fpm the_execution_engine stream;
```

https://llvm.org/docs/tutorial/OCamlLangImpl4.html

**Comment by ivg** [comment]
While I overall like the idea and we will soon start working on pushing the semantics the other way around, i.e., reifying BIL to machine code, the premise "Since LLVM is the core BAP dependency" doesn't really hold. In fact, it would be a major problem for us, since the `llvm` package in opam conflicts with the system LLVM library. We're using the system LLVM library, but the `llvm` package downloads llvm from source and builds the bindings (the same way as z3 does). Therefore, the easiest solution, if we would ever decide to use llvm for code generation, would be just to use the `llvm` package independently of the already used system LLVM library (up to be able to use two different versions, one for disassembling and another for assembling at the same time). This approach (and so far I don't see any other) will basically introduce a new huge dependency and roughly will double the build times. 

With that said and to continue the discussion, I am not really sure that LLVM suits our needs for the purposes of JIT compilation and, which is more interesting for us, binary rewriting. Well, at least the code generation layer. It is not fine-granular enough and doesn't give enough control on the generated code as it operates totally on the LLVM IR level and reserves a lot of freedom for itself in the way how it generates the code, which is perfectly fine for the compiler toolchain but is not for specialized tools such as binary rewriters and microexecutors. 

For JITed microexecution, I think it is better to use MetaOCaml, though I doubt that we will get any real benefits in Primus given how many injection points we have in each Primus computation. I can only envision JIT compilation of primitives, especially those of SIMD, but basically, everything that we will decide to JIT compile should become an unobservable non-monadic black box, which limits the applicability of JIT/Meta compilation to Primus.  

Concerning code generation, we should stay away from LLVM IR and, instead, we can reuse the LLVM MC framework for fine-granular instruction emission. And this layer doesn't have OCaml bindings, so we will have to eventually create them.

**Comment by ivg** [comment]
I am closing this as there is no need for Primus to have a JIT compiler (it won't make things faster but definitely complexify them). But we need, in general, a reification to machine code for binary rewriting, patching, and, potentially, executing. We are currently working on it and hope to deliver it in the next few releases.
