### ISSUE TITLE
emulating BIL?

### ISSUE THREAD

**Issue by aug2uag** [BinaryAnalysisPlatform/bap#1292]
I truly enjoy the outputs from `-dbir` and `-dbil` and so grateful for your representation.

Are there any works, plans, or projects relating to emulation or dynamic binary translation from the immediate language or representation?

**Comment by ivg** [comment]
Sure, we have a microexecution framework called [Primus][1]. You can run a program using the `--run` command-line option.

[1]: https://binaryanalysisplatform.github.io/bap/api/master/bap-primus/Bap_primus/Std/index.html

**Comment by aug2uag** [comment]
Would you happen to have an example where a .bir or .bil file may be executed by Primus? I'm particularly interested in fuzzy hashing. After reviewing documentation it's not clear (for me; new to this domain with no prior experiences in monads or OCaml) how to start.

I tried the following:
```
$ bap /rb/buggy -dbir > out.bir
$ bap ./out.bir --run
Failed to build the project:
File format is not supported

$ bap /rb/buggy -dbil > out.bil
$ bap ./out.bil --run
Failed to build the project:
File format is not supported

```

**Comment by ivg** [comment]
Sorry, I didn't notice your comment. You need to run the binary directly (there is no need to created intermediate files), e.g.,

```
bap ./exe --run
```

Will run (emulate) the binary, much like qemu user mode. Note, if you will try `bap /bin/ls --run` you won't get the directory listing as we missing a few stubs for /bin/ls to work. But we can run quite complex binaries, like the [echo][1] binary which we compile to different architectures to test that our lifting is correct. 

We use Primus, however, not only for running binaries (which is mostly useful for tests). The main raison d'être of Primus is to run fuzz-like analyzes, especially of programs that we can't run natively. Primus is an interpreter framework and there is one feature that make it stand apart from any other interpreter. It is a non-deterministic interpreter (in a sense that's the computational model that it implements is Non-deterministic Turning Machine). This approach makes it easy to write analysis that usually have to deal with NP hard problems and it hides the problem of path-explosion from the user analysis, so that a user is only facing one path at a time.  Another interesting feature of Primus is that it has an embedded Lisp Machine that lets your write analysis or stubs to missing functions (in fact any code) in Primus Lisp (a special dialect of Lisp).  

For example, we can easily implement valgrind's memcheck analysis using Primus and Primus Lisp. We use Primus Lisp to define our [memcheck framework][2] and then we define the [memory safety policy][3] for malloc family of functions. Now, we can run it with `bap ./target-binary --run --primus-lisp-load=memcheck-malloc,posix` and we will get incident reports for each bug.  We even have a collection of tools [bap-toolkit][4] with some tools using Primus. Other than memcheck analysis we have also implemented various information flow analyses that rely on our Taint Analysis Framework; we have [check-value][5] for null-pointer derefernces, unchecked return values, and so on; we even use Primus to detect Spectre bugs in our [oo7][6] tool.

So Primus is very powerful and it is a lot here to learn. And you're welcome to try it and we will be here to help you, don't worry. Just don't hesitate to ask questions and poke me if am not replying :)  I would suggest you to drop by [our gitter channel][7] for the live discussion. It is much better than having to talk via the issue tracker. (I promise you won't be left unattended there). 





[1]: https://github.com/BinaryAnalysisPlatform/bap-testsuite/blob/master/src/echo.c
[2]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/plugins/primus_test/lisp/memcheck.lisp
[3]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/plugins/primus_test/lisp/memcheck-malloc.lisp
[4]: https://github.com/BinaryAnalysisPlatform/bap-toolkit
[5]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/plugins/primus_test/lisp/check-value.lisp
[6]: https://ieeexplore.ieee.org/document/8902081
[7]: https://gitter.im/BinaryAnalysisPlatform/bap

**Comment by ivg** [comment]
You're very welcome to drop by our Gitter [channel][1] if you have any questions. 

[1]: https://gitter.im/BinaryAnalysisPlatform/bap
