### ISSUE TITLE
Unable to resolve function external:malloc with ARM Big Endian

### ISSUE THREAD

**Issue by FactionCube** [BinaryAnalysisPlatform/bap#1324]
I have tried to run a simple primus script on the `echo` binary mentioned previously in issue #1299.  This binary is from a `uclib` repository, is big endian and `armv1`.   The `scm` script I am running is this one:
```
(option primus-lisp-load
  posix
)

(option passes
        run)

(option report-progress)
(option log-dir log)

(option primus-print-output incidents)
(option primus-greedy-scheduler)

(option primus-print-obs
        call
        incident
        incident-location)
```

The output I get is this:
```
bap ./echo --recipe=simple_run.scm

[00:00:00]  disassemble: 100% (3/3)
[00:00:00]  run: 100% (2/2)
The job `multi-task' finished abnormally with an exception:
unable to resolve function external:malloc, because no suitable definitions were found.
The following candidates were considered:
All definitions with the given name:
File "/home/user/.opam/4.10.0/share/bap/primus/site-lisp/simple-memory-allocator.lisp", line 52, characters 0-618
All definitions applicable to the given context:
File "/home/user/.opam/4.10.0/share/bap/primus/site-lisp/simple-memory-allocator.lisp", line 52, characters 0-618
Definitions that are most specific to the given context:
File "/home/user/.opam/4.10.0/share/bap/primus/site-lisp/simple-memory-allocator.lisp", line 52, characters 0-618
All definitions applicable to the specified arguments:
No definitions
Note: the definitions were considered in the following context:
(context (abi :unknown) (arch armv7eb) (bits 32) (byte 8) (code-addr-size 32)
 (component bap-internal:legacy-main-component-1
  bap-internal:legacy-main-component-10 bap-internal:legacy-main-component-11
  bap-internal:legacy-main-component-12 bap-internal:legacy-main-component-13
  bap-internal:legacy-main-component-14 bap-internal:legacy-main-component-15
  bap-internal:legacy-main-component-16 bap-internal:legacy-main-component-17
  bap-internal:legacy-main-component-18 bap-internal:legacy-main-component-19
  bap-internal:legacy-main-component-2 bap-internal:legacy-main-component-20
  bap-internal:legacy-main-component-21 bap-internal:legacy-main-component-22
  bap-internal:legacy-main-component-23 bap-internal:legacy-main-component-24
  bap-internal:legacy-main-component-25 bap-internal:legacy-main-component-3
  bap-internal:legacy-main-component-4 bap-internal:legacy-main-component-5
  bap-internal:legacy-main-component-6 bap-internal:legacy-main-component-7
  bap-internal:legacy-main-component-8 bap-internal:legacy-main-component-9
  bap:load-binary)
 (data-addr-size 32) (endian big) (endianness core:eb) (fabi :unknown)
 (filetype :unknown) (system :unknown bap:legacy-main)
 (target :unknown arm armv4+eb armv5+eb armv5t+eb armv5te+eb armv5tej+eb
  armv6+eb armv6t2+eb armv7+eb))
```

I wasn't sure how to resolve the missing malloc function.  

I had similar problems with running `primus` on a similar `armeb` binary, which could not find a compatible `main` prototype (I don't have that sample here to share).

`bap` is otherwise handling `armeb` well.

I can append the `echo` binary here if requested, though it is available on the #1299 issue page.

Regards to you all.

**Comment by ivg** [comment]
The issue is that we're missing the armeb-gnueabi implementation<sup>1</sup>, so the malloc function has zero arguments,
```
bap echo -d | grep 'sub malloc'
0000686e: sub malloc()
```

and as a result the function resolution fails as there is no malloc implementation that has zero arguments (Primus Lisp allows function overloading). Basically the error message,
```
All definitions with the given name:
File "/home/user/.opam/4.10.0/share/bap/primus/site-lisp/simple-memory-allocator.lisp", line 52, characters 0-618
All definitions applicable to the given context:
File "/home/user/.opam/4.10.0/share/bap/primus/site-lisp/simple-memory-allocator.lisp", line 52, characters 0-618
Definitions that are most specific to the given context:
File "/home/user/.opam/4.10.0/share/bap/primus/site-lisp/simple-memory-allocator.lisp", line 52, characters 0-618
All definitions applicable to the specified arguments:
No definitions
```
says, we have one definition (in simple-memory-allocator:52) that matches the name. This definition is matching the context. It is also the most specific definition out of the set of all known definitions (kind of trivial for a set of one definition) and we have zero definitions that are applicable to the specified arguments. 

----

<sup>1)</sup> I am working on it. Another issue is that we don't have byteweight signatures trained on armeb files. Do you have a set of armeb artifacts with debugging symbols?

**Comment by FactionCube** [comment]
Thank you Ivan.  So, if you had armeb artifacts, then that would supply missing function prototypes for byteweight, yes?  I don't have any to hand, but I'll look around online.  I wouldn't mind learning how to use byteweight as you never know if this sort of issue might pop up again some day.   Regards, and thank you.

**Comment by FactionCube** [comment]
I did find non-stripped compiled binaries on this page:  https://releases.linaro.org/components/toolchain/binaries/latest-5/armeb-linux-gnueabi/  and I downloaded file `sysroot-glibc-linaro-2.21-2017.10-armeb-linux-gnueabi.tar.xz` which has files like this:

  `libc-2.21.so: ELF 32-bit MSB shared object, ARM, EABI5 BE8 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux.so.3, BuildID[sha1]=35ee4e551e57db7e47799a28d705b7c8986363d9, for GNU/Linux 2.6.32, with debug_info, not stripped`

So I guess you just apply `byteweight train` to these binaries?

**Comment by ivg** [comment]
> By the way, another tar file I found there had a mix of x86_64 and armeb binaries, so one presumably cannot simply run byteweight across a folder without first selecting only files which are armeb. Is this correct?

Yes, it is correct, you can either remove non-armeb binaries or train on all and then just edit the resulting zip file and remove x86 signatures. 

You can also consider making a  PR to [arm-binaries][1] with the corpora so that later we can retrain signatures, in case if that need (e.g., new algorithm, more data, etc). 


>  but I'll see if I can cross-compile some kernel code

I am not sure that kernel calling conventions match with the user-mode calling conventions. It is good to  have both in the signatures but it is important to have them correspondingly represented so that byteweight do not graviate to one or another (or if graviate then proportionally to the corresponding probability of kernel vs user-mode code). 


[1]: https://github.com/BinaryAnalysisPlatform/arm-binaries
