### ISSUE TITLE
bap fails to disassembled MIPS MSB binaries

### ISSUE THREAD

**Issue by bin2415** [BinaryAnalysisPlatform/bap#1407]
Hello, I want to use bap to disassemble mips binaries. But bap fails to identify any instruction of my binary code which is not striped. I wonder if I miss some important steps.

Below is my steps:

```bash
docker pull binaryanalysisplatform/bap:latest

bap --version
$ 2.5.0-alpha+cdc8248

bap -d -dasm ./yes
$ 0000006a: program

file ./yes
$ yes: ELF 64-bit LSB shared object, MIPS, MIPS64 rel2 version 1 (SYSV), dynamically linked, interpreter /lib64/ld.so.1, for GNU/Linux 3.2.0, BuildID[sha1]=8dada9fd537052130e2b49e527c938c7e3207680, with debug_info, not stripped
```

The binary I used is [yes.zip](https://github.com/BinaryAnalysisPlatform/bap/files/7885942/yes.zip)

Thanks in advance!

**Comment by ivg** [comment]
Nothing should be done, it should work out of the box. It looks like that we have a small bug, or rather a missing feature, which enables big-endian mips files. I will fix asap and the new docker image will be available tomorrow (if this issue will be closed by the end of the day). Thanks for reporting it!

**Comment by ivg** [comment]
The fix is out, see #1408. But notice that you're probably the first person using BAP on little-endian MIPS binaries, we only tested it on big-endian binaries. Beside, do you know what toolchain was used to build them?

Also, the MIPS lifter is not complete, though you might try using the ghidra backend which provides much more complete lifter at the expense of bloated code, you can use `--optimization-level=3` to debloat it, but it will still be far from optimal. We are currently working on it. To enable the Ghidra based lifter for mips you need to pass `--mips-backend=ghidra`, e.g.,
```
bap yes  --mips-backend=ghidra -d
```

And feedback on how bap works with mipsel is very welcome :)

**Comment by bin2415** [comment]
Great! Thanks for your help.

> do you know what toolchain was used to build them?

Yeah, there is a debian docker for [mips64el](https://hub.docker.com/r/mips64le/debian). Its dependency is [multiarch](https://github.com/multiarch/qemu-user-static).

**Comment by bin2415** [comment]
Great! Thanks for your help.

> do you know what toolchain was used to build them?

Yeah, there is a debian docker for [mips64el](https://hub.docker.com/r/mips64le/debian). Its dependency is [multiarch](https://github.com/multiarch/qemu-user-static).
