### ISSUE TITLE
make BIL serializing pluggable 

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#177]
Currently we have piqi dependency hardcoded, plus a bunch of different formats. Although piqi now works, it may break up again, since it is barely supported. Moreover, we're moving in a direction of a more flexible installation process, with optional dependencies. 

Introducing a BIL serialization extension point in a plugin system will
1. allow us to make piqi dependency optional
2. allow users to introduce new serializers without need to modify BAP itself
3. give more flexibility in public API, by allowing a client to specify its own formats.

**Comment by KennethAdamMiller** [comment]
If Piqi based serialization becomes an optional dependency, so too the stmt specification will become optional in how it is maintained. To where will we look for an authoritative grammar specification of the BIL language if piqi is not used? We need to interpret BIL since our analyses are authored in languages other than OCaml. 

I admit there is certainly a disparity in supporting so many formats, and the burden should be less. Possibly however, we should advocate that formats that are most easily best supported should be what are, and others simply not. For instance, protobuf generates other vernacular representations for many languages, but xml and json is more of a red herring, since users adopting such would essentially fall back to authoring lexers-non ideal.

I'm looking to parse the ADT by authoring a grammar for it, so one to one support in can be made extensible and composable for various analyses by simply specifying actions in the grammar. Can this serve as a good example in how to correctly and accurately interpret BIL?

**Comment by dbrumley** [comment]
Hey kevin: interoperability is high on our list.  The main idea is to actually add flexibility for those looking to use other languages.  Out of curiosity, what language are you using?

**Comment by ivg** [comment]
Making it optional doesn't mean that we're going to forfeit it. It still be the part of the release, i.e., you will always be able to install it with opam, by `opam install bap piqi`. This is just to allow those, who are not interested in piqi serialization, not to install it. Because, piqi package may impose many conflicts on a system. Actually, it was unusable last 3 months, that is one of the reasons, why we previously removed piqi from the release.

What concerning ADT as a representation, first of all on wiki only the ADT format is specified, BIL by itself is left unspecified. The best available specification of a BIL in ADT format is a [bil](
https://github.com/BinaryAnalysisPlatform/bap/blob/master/python/bil.py) module in our python bindings. It is quite readable, and, more important, runnable specification.  Adt can be easily parsed from C++ even with hand-written parser, although I would recommend you to use either bison, or `boost::phoenix` to write a parser. What concerning specifying actions inside the parser, it is in general not a good idea. I would better suggest to write a first class representation of the BIL in C++. That would require you to implement a [Visitor pattern](http://en.wikipedia.org/wiki/Visitor_pattern) or (less general) [Interpreter](http://en.wikipedia.org/wiki/Interpreter_pattern). In general this will mimic python bil, i.e., you need to define class for `Stmt`, then to define a separate class for each branch of `Stmt` variant, e.g., `struct Move : Stmt {..}`. A good example of such code is [openreil](https://github.com/Cr4sh/openreil/blob/master/libasmir/include/stmt.h) project, that uses old BAP BIL in C++

**Comment by KennethAdamMiller** [comment]
@dbrumley I'm using C++, but predominantly because our emulator is authored in it and I don't want to discard code without justification. Speed is critical in an interpreter that does our amount of work, so it's not so bad.

A grammar to generate actions for a interpreter is exactly what I was looking to do. I identified it as a far higher quality deliverable allowing modularity and reuse of IL derived action specification (potentially pre-computed too!) in various analyses. You could potentially enumerate the instruction set in a table, and BAP decode each, then pipe that to the bison generated lexer that could possibly implement a an emulator action or pipe output to derive taint analysis specification statically... or other interesting analysis ideas? Thoughts?

I was working to grok bison last night until 4 am, but I don't think I can sell boost where I work. I was advised by NRL leader here to investigate pegging parsers since I do have deadlines. Thoughts? I'm familiar with using the visitor pattern specifically in providing variants of algebraic types appropriately in C++, (not sure if we're on the same page as to how that fits in) since obviously you would want compile time type discrimination in a grammar. If I can translate the BIL grammar into bison, I can probably do it for another language too.

Cool! Thanks for the pointers!

**Comment by ivg** [comment]
if deadline is pushing hard on you, then you can just parse ADT with a bunch of regular expressions

**Comment by ivg** [comment]
You can take a look at how I partially parse ADT format in OCaml, using regular expressions: https://github.com/BinaryAnalysisPlatform/bap/blob/master/src/server/adt.ml#L58

**Comment by KennethAdamMiller** [comment]
This is a nice reference point I can fall back to should bison not pan out, thank you so much! I can at least make a stab at bison having made it this far. I strive hard to produce reusable, high quality results, and I like to do things once and conquer them before moving on.

**Comment by KennethAdamMiller** [comment]
Oops, specifications in a parser not a good idea, missed that tidbit.

**Comment by ivg** [comment]
done in #344
