### ISSUE TITLE
Creating a CFG

### ISSUE THREAD

**Issue by Raul-Gomezcana** [BinaryAnalysisPlatform/bap#192]
Hi, I've installed BAP and I'm able to run the Python examples from the README. Is there a way to generate a CFG using Python? If not, what are the steps to generate a CFG from an executable?

**Comment by ivg** [comment]
CFG reconstruction is not yet exposed via public api and, hence , python bindings. The algorithm is basically [described here](http://reverseengineering.stackexchange.com/questions/2347/what-is-the-algorithm-used-in-recursive-traversal-disassembly). Although you can try to look into qira code. Or better switch to OCaml))

**Comment by Raul-Gomezcana** [comment]
Thanks for the response. So if I use OCaml, is there a function in BAP that
creates the CFG? I was searching around and saw that on previous BAP
versions there was an iltrans tool that did this.

**Comment by ivg** [comment]
Sure it is. First of all there is a `bap` tool, that can be used to disassemble explore your binaries. Of course it reconstructs CFG, that can be printed in different formats, including dot. If you need more, you can write a plugin, that will get an immediate access to the whole disassembled program, including CFG, symbol tables and BIL. 
And also you can play with bap library directly, getting cfg is as easy as:

```
utop # open Bap.Std;;
utop # let d = disassemble_file "ls";;
```

**Comment by Raul-Gomezcana** [comment]
Thanks, but after that I'm lost. I've tried searching for more examples or some documentation but couldn't find anything.

When you get a chance could you please post the commands to go from the disassembled file to print out the CFG into dot format?

**Comment by KennethAdamMiller** [comment]
Using the options for readbin and reading the help that it provides, it specifically tells you that it does CFG recognition on your behalf. If that doesn't suit your case, and you need to specialize specifically for your use case.

Looking just briefly in bap_diasm.mli, you can see that the type returned by the disassemble_file function is defined opaquely as disasm, and the mli provides introspection functions that allow you to peer into the record fields.

From there you can see that there is a block member of the appropriate type that can be used interchangeably with the functions provided to you at least in bap_disasm_block.ml(i). Transforming OCamlgraph into dot format is as little work as just reading the ocamlgraph API documentation on their website, but likely there are goodies in bap for that already. What graph specifics you choose I leave to you, as you know your use cases and likely are more suited to make decisions that suit you best there.

Also, documentation for bap can be generated by cloning it, make -j5 && make doc, and look in bap.docdir

**Comment by ivg** [comment]
First of all I've uploaded latest [documentation](http://binaryanalysisplatform.github.io/bap/api/v0.9.6/experimental/ocamldoc/Bap.Std.html). 

Next, if you just want to look at CFG, there is a `--phoenix` option in `bap` utility, that will dump a whole bunch of graphs for each function. But I suppose, that you want to build them programmatically yourself. In this case the easiest way would be to use `Block.to_graph` function to obtain a graph, and then use an ocamlgraph's library to dump it in dot format. The first approximation, would be the following:

```ocaml
module CFG = struct
  include Block.Cfg
  let vertex_name b = 
    sprintf "%S" (Addr.string_of_value (Block.addr b))
  let graph_attributes _ = []
  let default_vertex_attributes _ = []
  let vertex_attributes _ = []
  let get_subgraph _ = None
  let default_edge_attributes _ = []
  let edge_attributes _ = []
end
```

Here all functions are stubs, except the `vertex_name` that transforms values of type `block` into strings.

Dumping into file is easy
```ocaml
let save_to_file ?bound blk =
  let module Dot = Graph.Graphviz.Dot(Callgraph) in
  Out_channel.with_file "callgraph.dot" ~f:(fun chan ->
      Dot.output_graph chan (Block.to_graph ?bound blk))
```

The next step is to find a good candidate block, that will produce a cfg for your. 
To get a set of program blocks, you need to disassemble the binary. You can do it either manually, with `disassemble_file` function, or, register, your program as a plugin, and get an access to already disassembled binary. The latter is recommended because it will give you an access to symbol tables for free (but of course, you can reconstruct symbols yourself, with `Symtab.create` function). 
You can use `bap --help` to get the general idea on how to create and use plugins. 

Here is the full example of a plugin, that will output a CFG for a given function (didn't tested it):
```ocaml
open Core_kernel.Std
open Bap.Std
open Project

module Callgraph = struct
  include Block.Cfg
  let graph_attributes _ = []
  let default_vertex_attributes _ = []
  let vertex_name b = 
    sprintf "%s" (Addr.string_of_value (Block.addr b))
  let vertex_attributes _ = []
  let get_subgraph _ = None
  let default_edge_attributes _ = []
  let edge_attributes _ = []
end

module Cmdline = struct
  open Cmdliner
  let symbol : string Term.t = 
    let doc = "symbol name for which to build the CFG" in
    Arg.(required & opt (some string) None & 
         info ["symbol"] ~doc)

  let info = 
    Term.info ~doc:"Output a CFG for a given graph" "cfg"

  let parse argv : string = 
    match Term.eval ~argv (symbol,info) with
    | `Ok sym -> sym
    | _ -> exit 1

end 

let find_entry proj sym = 
  let open Option.Monad_infix in
  Table.find_mapi proj.symbols ~f:(fun mem sym' -> 
    Option.some_if (sym = sym') mem) >>= fun mem -> 
  Table.find_addr (Disasm.blocks proj.disasm) (Memory.min_addr mem) 
  >>= fun (_,blk) -> Some (mem,blk)

let main argv proj =
  let module Dot = Graph.Graphviz.Dot(Callgraph) in
  let symbol = Cmdline.parse argv in
  match find_entry proj symbol with
  | None -> eprintf "No such symbol in binary: %s\n" symbol
  | Some (bound,entry) -> 
    let name = sprintf "%S.dot" symbol in
    let _,graph = Block.to_graph ~bound entry in
    Out_channel.with_file name ~f:(fun chan ->
        Dot.output_graph chan graph)

let () = register_plugin_with_args' main
```
 
put this into `cfg.ml`

compile with `bapbuild`:

```sh
$ bapbuild cfg.plugin
```

run with `bap`:

```sh
$ bap yourbinary -lcfg --cfg-symbol=yoursymbol
```

**Comment by Raul-Gomezcana** [comment]
Thanks a lot, that's exactly what I needed!
