### ISSUE TITLE
A stupid question for a beginner: what is "|>" in the code?

### ISSUE THREAD

**Issue by jordychen** [BinaryAnalysisPlatform/bap#248]
Hi~ It seems that I could find anything about this symbol "|>" in several OCaml books. Is it a simplification of "match ... with ..."??

**Comment by KennethAdamMiller** [comment]
It's an infix operator, it just feeds the output of one operation to the next function going from left to right so you don't have to nest everything deeply in parenthesis and so that code is more legible.

Piqirun.to_string (Bapservice_piqi.gen_memory_dump dump)

is the same as:

Bapservice_piqi.gen_memory_dump dump |> Piqirun.to_string

But is easier for humans because it reads more fluidly.

If you get merlin in Emacs, you can inquire about the type definition of the infix operator, although if you've supplied it anything that the compiler can infer a polymorphic type to, it will automatically supplant the more general specification in the process of type inference. It's definition is something along the lines of 'a |> 'b

Also, the caml mailing list and google group is probably much more suitable for this. In addition to that, you can join the #ocaml irc channel on freenode.

**Comment by ivg** [comment]
it is also called a reverse application operator it may be defined as `let (|>) x f = f x`. There is also an application operator, defined as `let (@@) f x = f x`

**Comment by jordychen** [comment]
Got it! So kind of you, thanks for your help.

**Comment by jordychen** [comment]
Sorry to bother again, where did you define the operator ">>=" in ocaml? And what does it mean? I really don't know how to work with emacs and merlin with it.

**Comment by maverickwoo** [comment]
This is called the "bind" operator and, depending on which module you have most recently opened, it can mean very different things. BAP uses a lot of `Or_error` and so if you see `>>=` in BAP I would guess it is `Or_error.bind`. I highly recommend reading Real World OCaml to learn about OCaml and the book is freely available online. Chapter  7 has some explanation of the bind operator using `Option`.
https://realworldocaml.org/v1/en/html/error-handling.html

**Comment by KennethAdamMiller** [comment]
Right. BAP makes use of infix operators in general, they are in the infix
module provided by core_kernel. Once you understand modules, you can grasp
how reusable code can be, and the consequences of their meaning in
different contexts. Merlin would help with that too.
