### ISSUE TITLE
Reaching definition analysis

### ISSUE THREAD

**Issue by riyadparvez** [BinaryAnalysisPlatform/bap#253]
Is it possible to do reaching definition analysis in BAP? Since BAP has its own SSA form intermediate language, it should be doable. Any pointer should be appreciated.

**Comment by ivg** [comment]
The easiest way would be to transfer program into `SSA` form. After this it is quite trivial, as all uses are reachable. Currently SSA transformation  is released as a [plugin][1]. (It will be merged into BAP in 0.9.9). 

The workflow is the following:
1. clone the repository with plugins to folder $PLUGINS
2. start your own project in folder $PROJ, by creating a file $main.ml
3. compile ssa plugin
```
$ cd $PLUGINS/ssa
$ bapbuild ssa.plugin
```
4. Code your plugin, don't foget to request `ssa` as a dependency:
```ocaml
let rdefs proj = 
   (* do  something *)
   proj

let () = Project.register_pass ~deps:["ssa"] "rdefs" rdefs
```

5. Run your code 
```sh
$ bap -L$PLUGINS/ssa -l$main your_testing_binary
```

Do not forget to substitute variables, designated with `$` to real paths.

If you don't want to use a plugin system, then just download `ssa.ml` file and put it into the same folder as your code. And use it directly. You may find this two functions from `ssa.ml` useful: `ssa_sub` and `ssa_program`. To get the program in IR, use a family of functions `Project.from_*`. The easiest is to use [`Project.from_file`][2]. But make sure that your testing binary has enough symbol information, otherwise you will need to invoke byteweight searching algorithm. 

Also, `ssa.ml` requires the latest `bap` from master branch. Follow this [instructions][3] to get the latest version. 

[1]: https://github.com/BinaryAnalysisPlatform/bap-plugins/tree/master/ssa
[2]: http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Project.html#VALfrom_file
[3]: https://github.com/BinaryAnalysisPlatform/bap/wiki/Build-tips-and-tricks#getting-latest-development-version

**Comment by riyadparvez** [comment]
Thanks for the detailed reply!

It seems like a BAP plugin [1] has almost everything done. I've no idea of OCaml or IDA the readme mentioned. How much needs to be modified to make it "reaching definition"?

[1] https://github.com/BinaryAnalysisPlatform/bap-plugins/tree/master/data-dependency

**Comment by ivg** [comment]
Yes, this plugin computes reaching definition. This is somewhat unofficial plugin, and I can't say anything about this. 

P.S. OCaml is a language in which BAP is written and in which plugins must be written. IDA is a state of art tool for reverse engineering and program analysis.

**Comment by riyadparvez** [comment]
Yeah, I was just wondering whether learning OCaml just for BAP would be worthwhile.

Anyway, I'm getting the following error for some addresses in a binary when I'm trying to use the dataflow plugin. Can you tell me what this error means? 

> Aborting because (lib/bap/bap_project.ml.Pass_failed
>  (Runtime_error data_deps
>   ("Data_deps.Can't_handle(\"More than one function for addr \\\"0x8049B32:32\\\",can't handle this!\")"))).

**Comment by ivg** [comment]
I didn't write this plugin, and didn't even look at it, so I may only guess. According to message memory at address `0x8049B32` is shared between more that one function. Maybe, plugin author made wrong assumptions.

P.S. Learning OCaml is worthwhile in any case :)

**Comment by rvantonder** [comment]
Looks like you ran into an unhandled case for this plugin, namely, BAP believes there's more than one function at this address (a possibility with with some binaries). Another possibility (and I suspect more likely in this case) is that functions are not being resolved by IDA (using the `--use-ida` option), and BAP's fallback options are identifying multiple functions here.
