### ISSUE TITLE
The opam file is annoying

### ISSUE THREAD

**Issue by Drup** [BinaryAnalysisPlatform/bap#259]
- It lists as mandatory numerous optional dependencies, including the web server part
- the depext are completely wrong, you should NOT list transitive depexts.

**Comment by ivg** [comment]
There are good reasons for both. 

1. There is a political decision made by our group, to deploy bap into opam with "batteries included". We understand, that we can make opam file more flexible. But with an implication, that it will be much more harder for a new user to install bap, and it will be much harder for us to support it. Also, since most of the time this flexibility is needed only for power users, they still can install bap either through sources, using flexible `configure` script, or clone the repository and change `opam` file to their needs.

2. We know about this. But, for a long time, many of our dependencies did not list their external dependencies correctly, so we decided to enumerate them explicitly. Other reason, is that depext plugin is quite new (only few weeks old) and doesn't work on many installations and older opam versions. So, that we're using this transitive closure of external dependencies to install them manually on such systems.

**Comment by Drup** [comment]
You can do solve 1. pretty simply, just add messages in opam advertising the depopts.

**Comment by Drup** [comment]
(and potentially, change the command line advertised on your various tutorials)

**Comment by ivg** [comment]
No, that will not work. Believe me. Later when we will reach version 1.0 we will split bap into sub-libraries, e.g., bap-core, bap-toolkit, `bap-server`, etc. But `bap` will be still delivered as all-in-on package, since BAP stands for Binary Analysis Platform. 

Also, you must understand that there is an extra cost in supporting several libraries. That we don't want to pay right now.
