### ISSUE TITLE
support for rep prefix

### ISSUE THREAD

**Issue by rsinha** [BinaryAnalysisPlatform/bap#270]
I am working with code that frequently uses rep stos instruction.
While BAP seems to handle stos, the rep prefix does not seem to go through BAP, and I get an exception.
Would it be possible to add support for rep? I don't mind working on it, but any pointers would be very helpful.

**Comment by ivg** [comment]
Can you provide an example? 
`rep` prefix is handled as a separate instruction, i.e., `rep stos` should be handled as a pair of instructions. It is quite possible, that it is not handled correctly in a lifter though. So, when you're saying unhandled, do you mean that BIL is incorrect, or you're talikng about disassembly only?

**Comment by rsinha** [comment]
Apologies for the confusion. The lifting seems to fail. Here is the example.
echo 40574881ec80010000488b05302000004889842450010000488d44241048c1e8064889842458010000488d44241048c1e8034883e007b90500000048898c24600100000fb6c8488b84246001000048d3e0488b8c2450010000488b94245801000048090411488d4424204889842440010000488d4424104889842448010000488b842440010000488b8c24480100008b098b0003c183c02189842468010000488b0d9a1f000048898c2470010000488d4c243048c1e906488b9424700100004803d14889942478010000488d4c243048c1e9034883e107b2fed2e20fb6ca488b942478010000200a488b8c247801000048ffc9488bf933c0b901000000f3aa8b8424680100004881c4800100005fc3 | bap-mc --show-bil --addr=0x0000000000001000
At address 0x10fd, there is a rep stos instruction, and the lifter throws the following exception at that point. "Lifting failed: segfault: you missed a byte"

**Comment by ivg** [comment]
This is a bug that need further investigation. Some mismatch between old lifter and new disassembler backend. 
By the way, are you interested in bil itself or you just in a disassembler? In the latter case we can workaround, and remove unnecessary lifting.

**Comment by rsinha** [comment]
I am interested in lifting this code to bil in order to do some static analysis.
In case this fix needs significant changed within BAP, I am considering a temporary workaround of replacing "rep stos" with a Bil.Special instruction, so that my plugin can do special handling of these instruction. What do you think? This might allow us to just fix the disassembler (as you mentioned).

**Comment by ivg** [comment]
>  I am considering a temporary workaround of replacing "rep stos" with a Bil.Special instruction (in my own fork of BAP)

This is a possible way to do this. So we can try it, in case if it would take more than one week to handle the issue. 

Basically, the main problem, is that x86 lifter has its own disassembler embedded into it. It ignores the results of llvm-disassembler, and works directly on byte-level (unlike a more modern ARM lifter). So, there is a mismatch between this two disassemblers. Since lifting process is driven by llvm disassembler the former decides how many bytes are occupied by an instruction. In this case, llvm gives only one byte for the instruction, but built-in disassembler expects at least two. One of the easy solutions, would be to soften this interaction, and allow a lifter to access more memory, than required.

**Comment by ivg** [comment]
this will be fixed  as soon as new [x86-lifter](https://github.com/ivg/x86-lifter) will be merged
