### ISSUE TITLE
lock cmpxchg not lifted correctly

### ISSUE THREAD

**Issue by facuman** [BinaryAnalysisPlatform/bap#296]
Instruction: lock cmpxchg [ebx], ah
Opcode: F0 0F B0 23

Steps to reproduce: 

1) bap-mc --arch=x86 --show-bir=bir "F0 0F B0 23"
Output: "Lifting failed: segfault: you missed a byte"

BAP 0.9.8

**Comment by ivg** [comment]
This issue is three fold :)

0. You should use the latest 0.9.9 version, where `bap-mc` doesn't exit with error if instruction is not lifted.

1. Prefixes are currently not supported by our legacy x86 lifter. There is an ongoing work to fix this issue by implementing a new [x86 lifter](https://github.com/ivg/x86-lifter). It handles prefixes correctly, but here we have the second problem...

2. `cmpxchg` opcode is not supported yet.

**Comment by facuman** [comment]
okis, thanks for the answer!

**Comment by ivg** [comment]
@feseal, can you confirm, that the new lifter now handles this issue?
