### ISSUE TITLE
Identifying system calls 

### ISSUE THREAD

**Issue by jgarci40** [BinaryAnalysisPlatform/bap#319]
I would like to determine the points in a binary where system calls are made. However, I notice that I am only obtaining statements that look like this:

```
00000025: call @sub_400600 with return %00000016
```

Is there a straightforward way for me to determine what system call may be invoked at such a point using bap? For example, the above call for the simple binary under analysis should be either a fork, exec, open, write, or exit.

**Comment by ivg** [comment]
The system calls are rarely made by a user code directly. Usually they arse wrapped by a library calls. For example, read(2) is made inside the libc library read(3) function. Usually, the code for libraries are not included in the binary, since most of the binaries are dynamically linked. And even statically lonked binaries, still tries not to linkin the libc. 
To summarize, you will rarely see syscalls in regular binaries.

**Comment by jgarci40** [comment]
Since I'm interested in examining potentially malicious binaries, to 
what extent would I be able to extract at least the name of a function 
call, using bap, in the type of case I described previously?

**Comment by ivg** [comment]
if a function is not imported or exported from a binary, then there is no name information associated with it. Since c library functions are usually imported, their names are discovered, as well as names of other dynamically linked functions. IDA has a FLIRT algorithm that can discover names of some known functions, by a pattern matching on their binary representation. We can benefit from it, by `--use-ida` command line option. Of course, this requires the IDA.

**Comment by jgarci40** [comment]
I see. Thanks for the info!

I also noticed that objdump with the -d option can retrieve the system-call names. The addresses identified by bap and objdump seem to be matching. I think I can combine information from both tools.

**Comment by ivg** [comment]
Well, `objdump` shouldn't report more syscalls, than bap. Because, the calls are not in the binary, but inside libraries. On the other hand, if there is indeed a syscall in the binary (some compilers embed runtime support code, that contains syscalls), then bap will report it as an `int X` BIL instruction, where `X` is the number of the syscall, and `int` stands for interrupt. We will not reveal names, as they are very platform specific.
