### ISSUE TITLE
Install fails on OS X 10.11.2

### ISSUE THREAD

**Issue by stharding** [BinaryAnalysisPlatform/bap#331]
I'm trying to install bap using the instructions in the README. I have XCode and the command line tools installed, `clang++ --version` outputs `Apple LLVM version 7.0.2 (clang-700.1.81)`. At first I thought my problem might be related to #320, but it looks like that error had to do with the `memory` header file not being found. Here is the output of `opam install bap` on my system:

    The following actions will be performed:
      ∗  install bap 0.9.9
    
    =-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
    [bap] Archive in cache
    
    =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
    [bap: ./configure] Command started
    [ERROR] The compilation of bap failed at "./configure
            --prefix=/Users/harding/.opam/4.02.1 --with-cxx=`which clang++`
            --mandir=/Users/harding/.opam/4.02.1/man".
    [bap: ocamlfind remove] Command started
    [bap: ocamlfind remove] Command started
    [bap: rm] Command started
    [bap: rm] Command started
    [bap: rm] Command started
    [bap: rm] Command started
    [bap: rm] Command started
    [bap: rm] Command started
    [bap: rm] Command started
    [bap: rm] Command started
    [bap: rm] Command started
    [bap: rm] Command started
    [bap: rm] Command started
    
    #=== ERROR while installing bap.0.9.9 =========================================#
    # opam-version         1.2.2
    # os                   darwin
    # command              ./configure --prefix=/Users/harding/.opam/4.02.1 --with-cxx=`which clang++` --mandir=/Users/harding/.opam/4.02.1/man
    # path                 /Users/harding/.opam/4.02.1/build/bap.0.9.9
    # compiler             4.02.1
    # exit-code            1
    # env-file             /Users/harding/.opam/4.02.1/build/bap.0.9.9/bap-65852-1872ec.env
    # stdout-file          /Users/harding/.opam/4.02.1/build/bap.0.9.9/bap-65852-1872ec.out
    # stderr-file          /Users/harding/.opam/4.02.1/build/bap.0.9.9/bap-65852-1872ec.err
    ### stdout ###
    # [...]
    # pkg_lwt_log: ......................................... /Users/harding/.opam/4.02.1/lib/lwt
    # pkg_ezjsonm: ......................................... /Users/harding/.opam/4.02.1/lib/ezjsonm
    # pkg_uri: ............................................. /Users/harding/.opam/4.02.1/lib/uri
    # pkg_cohttp_lwt: ...................................... /Users/harding/.opam/4.02.1/lib/cohttp
    # pkg_re: .............................................. /Users/harding/.opam/4.02.1/lib/re
    # pkg_cmdliner: ........................................ /Users/harding/.opam/4.02.1/lib/cmdliner
    # pkg_re_posix: ........................................ /Users/harding/.opam/4.02.1/lib/re
    # pkg_curl: ............................................ /Users/harding/.opam/4.02.1/lib/curl
    # pkg_ocamlbuild: ...................................... /Users/harding/.opam/4.02.1/lib/ocaml/ocamlbuild
    # 
    ### stderr ###
    # E:   Failed to find llvm library, consider using --with-llvm-version
    #      or --with-llvm-config command line options, to point me on a
    #      correct version of LLVM. 
    
    
    
    =-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
    The following actions failed
      ∗  install bap 0.9.9
    No changes have been performed
    
    =-=- bap.0.9.9 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
    => This package relies on external (system) dependencies that may be missing.
       `opam depext bap.0.9.9' may help you find the correct installation for your
       system.
    
It complains that it couldn't find the llvm library, which is odd since it is definitely installed. The message suggests the `--with-llvm-config` or `--with-llvm-version` flags, but those are arguments to `./configure`. I'm not sure how to pass those along with `opam` or if there is even a way to do that. 

Here is a [gist](https://gist.github.com/stharding/218bae1733d906698be1) containing the output of `opam install bap --debug`

Any thoughts?

**Comment by ivg** [comment]
`bap` has few system requirements, that should be installed using system's package manager. We use `macports` for this (there rumors that other people use `brew` and also succeed). For `macports` the installation is automated, so that  `opam depext bap` will install everything needed. If you're using `brew` then you can try to install this manually, here is the list of external dependencies, in `macports` parlance (the up to date list can be viewed in the [opam][1] file):
```
["osx" "macports"] [
        "gmp"
        "llvm-3.4"
        "graphviz"
        "curl"
        "libzip"
     ]
```

[1]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/opam#L61

**Comment by ivg** [comment]
> It complains that it couldn't find the llvm library, which is odd since it is definitely installed. 

I will not be so sure. The `llvm-config` should be availabled (or `llvm-config-<ver>` or `llvm-config-mp-<ver>`  be available in the PATH. Also the version shouldn't be greater than `3.4`.

**Comment by stharding** [comment]
Ok, thanks for the feedback. I am indeed using `brew`. Looks like the LLVM 3.4 dependency is what's getting me. I tried `brew install homebrew/versions/llvm34` but that failed. I haven't had time to look into why that failed yet. In the long run I'm actually more interested in getting this working with the python hooks on debian so I'll probably transition my efforts there. I'll update this if I get it working with `brew` on OS X.

**Comment by ivg** [comment]
FUY: we're redesigning python hooks in a next release, so it is highly possible, that they will not work just after the release (python hooks are usually released afterwards). I'm currently collecting use cases for the python bindings, and it will be very helpful for me, if you will provide some feedback on python bindings. In particular in what functionality are you interested?

**Comment by stharding** [comment]
Thanks for the heads up. As far as the functionality I'm interested in, I'm investigating BAP as a tool to dynamically determine basic blocks in arbitrary binaries. I am contemplating modifying the genetic algorithm used in [this](http://dl.acm.org/citation.cfm?id=2768424) publication to use basic blocks as the units of mutation instead of what amounts to a line of assembly. The Algorithm currently uses `objdump` to determine offsets for potential mutation. I hope to use BAP to replace that part of the algorithm and experiment with some more sophisticated techniques.

**Comment by ivg** [comment]
> use basic blocks as the units of mutation instead of what amounts to a line of assembly

This is for sure can be done with BAP. Of course you can use python bindings for this. But this will have some overhead, so I would suggest you to try to use our extension mechanism to tailor `bap` frontend for your needs. Of course, you need to know OCaml for that, but it is an easy language to learn. For example, `bap` doesn't dump<sup>1</sup> basic blocks by default, but this feature can easily be added: you just need to create a file `blocks.ml` with the following contents

```ocaml
open Core_kernel.Std
open Bap.Std
open Format

let main proj =
  let blocks = Disasm.blocks (Project.disasm proj) in
  Table.iter blocks ~f:(fun blk ->
      printf "%a\n" Block.pp blk)

let () = Project.register_pass' "print-blocks" main
```

Then compile it with:
```
$ bapbuild blocks.plugin
```

And run it:

```
$ bap /bin/true -lblocks
```

or, if you're using a master version or not yet released 0.9.10, then:

```
$ bap /bin/true -lblocks --print-blocks
```

Here is the sample output:

```
$ bap /bin/true -lblocks --print-blocks
[401040, 401045]
[401050, 401055]
[401060, 401065]
...
```

<sup>1</sup>: Well, actually it can dump basic blocks, since we serialize functions as a sequence of basic blocks, that constitutes it. So, even without plugins you can get this information by using `--dump-symbols` option, e.g.,

```
$ bap /bin/true --dump-symbols
(sub_403c70 4209776 4209787)
(sub_403c70 4209798 4209801)
(sub_403c70 4209791 4209797)
(sub_403c70 4209788 4209790)
(sub_403c70 4199120 4199125)
...
```

In general the whole algorithm can be implemented using BAP as a platform, especially, with the presence of forthcoming `bap.dynamics` library, that will allow to run traces and other tools directly from bap. (We have some support for working with traces, but it will be much better in release 0.9.11, that is about in 2 or 3 months). 

Also, BAP has an interpreter, that can interpret lifted code. This can be used instead of tracing, as it gives you much more control over the code execution (at the price of speed, of course).

In any case, if you will need some specific feature feel free to poke us, either via issue tracker or gitter.

**Comment by stharding** [comment]
Fantastic, Thank you for pointing me in the right direction!

**Comment by cornerCao** [comment]
hell`hh`

**Comment by cornerCao** [comment]
> just for test
``why``
