### ISSUE TITLE
Trouble because bitstring lib has no unix.cma. 

### ISSUE THREAD

**Issue by caiannello** [BinaryAnalysisPlatform/bap#341]
I hope this is the proper forum for this. If not, apologies, and please advise.

In Ubuntu 14.04 LTS x64, I installed opam, ocaml, and BAP per the instructions:

$ opam init --comp=4.02.1
$ eval `opam config env`
$ opam install depext
$ opam depext bap
$ opam install bap

I had a failure with that regarding some packages:

[ERROR] The compilation of piqilib failed at "make". 
[ERROR] The compilation of ezjsonm failed at "make".

...but after looking through closed issues, I found that I could make those go away with the following:

opam upgrade 'lwt>=2.5.0' cohttp
opam install optcomp
opam install bap

which seems to have worked.

Using the python bindings, I am able to show disassembly of an aarch64 function from bionic libc, which is very cool to me. I want to try to work with BIL too.

I try to get started using utop:

utop
#use "topfind";;
...ok...
utop # #require "bap.top";;
Cannot find file /home/ubuntu/.opam/4.02.1/lib/bitstring/unix.cma.              Cannot load required shared library dllllvm_stubs.                              Reason: /home/ubuntu/.opam/4.02.1/lib/stublibs/dllllvm_stubs.so: /home/ubuntu/.opam/4.02.1/lib/stublibs/dllllvm_stubs.so: undefined symbol: del_curterm.
Cannot load required shared library dllllvm_loader_stubs.
Reason: /home/ubuntu/.opam/4.02.1/lib/stublibs/dllllvm_loader_stubs.so: /home/ubuntu/.opam/4.02.1/lib/stublibs/dllllvm_loader_stubs.so: undefined symbol: del_curterm.
Error: Reference to undefined global `Bap_llvm_loader'

"baptop" gives similar error.

Should I roll back the version of bitstring lib to the one you guys are expecting? If so, how can I do that?

Thanks,
Craig Iannello

**Comment by ivg** [comment]
That is kind of a very surprising output. I suspect, that you've done something very weird with your system, to get it. But lets move in a slower pace:

1. bitstring is innoncent here, this `unix.cma` is a confusing warning message, just ignore it  (it is already fixed in a new comming version)

2. `opam install optcomp` is not needed, it was a totally wrong advice (although not harmful), looks like that whoever advised it, thought that `optcomp` stands for optimized compiler, but it is `cpp` like preprocessor, that we have never used. The line that actually helped was the first one (`opam upgrade 'lwt>=2.5.0' cohttp`), although it is still kind of a weird advice...

3. Now to the problem itself. Are you absolutely sure, that you didn't mess with your `/lib` or `/usr/lib` folder? Like linking the `libncurses` or `libcurses` library? In particular do you have `/usr/lib/libncurses.so` file? (that you shouldn't have in normal Ubuntu installation). 

If not, then I can only suggest you to cleanup everything, and start accurately from scratch. Just removing your `.opam` folder will work. Then do the following:

```
opam init --comp=4.02.2
eval `opam config env`
opam install depext
opam depext bap
opam install 'lwt>=2.5.0' bap
```

P.S.

> Using the python bindings, I am able to show disassembly of an aarch64 function from bionic libc, which is very cool to me. I want to try to work with BIL too.

You will not see the BIL for aarch64, unfortunately. We support lifting only for ARM, x86 and x86-64.

**Comment by caiannello** [comment]
I'm very nearly a clean Ubuntu 14.04 LTS x64 install, except I had installed Valgrind.

I didn't find /usr/lib/libncurses.so, so instead I just removed .opam and followed your install instructions.

During "opam install 'lwt>=2.5.0' bap":

∗  installed type_conv.112.01.02
∗  installed bitstring.2.0.4
[ERROR] The compilation of piqilib failed at "make".
∗  installed comparelib.109.60.00
...snip...
∗  installed core_kernel.112.35.00

#=== ERROR while installing piqilib.0.6.6 =====================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/ubuntu/.opam/4.02.2/build/piqilib.0.6.6
# compiler     4.02.2
# exit-code    2
# env-file     /home/ubuntu/.opam/4.02.2/build/piqilib.0.6.6/piqilib-2353-1bb2ab.env
# stdout-file  /home/ubuntu/.opam/4.02.2/build/piqilib.0.6.6/piqilib-2353-1bb2ab.out
# stderr-file  /home/ubuntu/.opam/4.02.2/build/piqilib.0.6.6/piqilib-2353-1bb2ab.err
### stdout ###
# [...]
# set -e; \
# 	for dir in piqilib src; do \
# 		make -C $dir ; \
# 	done
# make[1]: Entering directory `/home/ubuntu/.opam/4.02.2/build/piqilib.0.6.6/piqilib'
# echo "let version = \"`head -1 ../VERSION`\"" >piqi_version.ml
# echo "version = \"`head -1 ../VERSION`\"" >META
# cat META.in >>META
# ocamlfind ocamlc -package ulex,easy-format,xmlm -c -pp "camlp4orf " -I +camlp4 pa_labelscope.ml
# make[1]: Leaving directory `/home/ubuntu/.opam/4.02.2/build/piqilib.0.6.6/piqilib'
### stderr ###
# [...]
# File "pa_labelscope.ml", line 29, characters 17-22:
# While expanding quotation "expr" in a position of "expr":
#   Parse error: illegal begin of quotation of expression
# 
# File "pa_labelscope.ml", line 1:
# Error: Error while running external preprocessor
# Command line: camlp4orf  'pa_labelscope.ml' > /tmp/ocamlpp32444d
# 
# make[1]: *** [pa_labelscope.cmo] Error 2
# make: *** [dirs] Error 2


Thanks for your help

**Comment by caiannello** [comment]
looking at https://github.com/BinaryAnalysisPlatform/bap/issues/286 ,  

maverickwoo commented on Aug 15, 2015
The error message suggests that somehow the constraint solver is missing optcomp. Please run opam install optcomp and try again.

which indeed does seem to help piqilib get installed.

`∗  installed piqilib.0.6.12
∗  installed piqi.0.7.4
`

**Comment by ivg** [comment]
ok, then let me apologize, this was indeed the issue with `optcomp`. So, please install it. 
What about the bap? Did the reinstallation from scratch helped to resolve the issue?

**Comment by caiannello** [comment]
baptop seems to start!  Thank you.
