### ISSUE TITLE
IDA Scanning

### ISSUE THREAD

**Issue by maurer** [BinaryAnalysisPlatform/bap#404]
Right now, BAP uses locate to find IDA, and does so on every command (even `bap --help`). On systems without IDA, this can lead to long hangs when trying to do simple, unrelated tasks.

Possible ways to make this better:

* Detect IDA via PATH
* Add a timeout to IDA locate command
* Detect whether IDA is available at installation time (still needs something other than locate, the locate would likely seem to be a hung install on e.g. pride)
* Create a `.baprc` or something similar, store configuration information on where IDA is there, default to assuming IDA is not installed. This could be combined with `bap --detect-ida` or some such invocation which would perform the locate or path search, and update the `.baprc` in order to avoid locates on future runs.

I understand that we want to default to using IDA when it is available, but the current approach is going to create a bad user experience for new users (who likely don't have IDA installed).

**Comment by ivg** [comment]
I think that the timeout is the best option. Usually, when it is not found in a first second, then it will not be found at all. We can emit a warning if we disable IDA by timeout. And an option to specify the timeout.

**Comment by ivg** [comment]
Also, we may just try to optimize the call to locate. First we can try to specify a more specific patter. For example, this query is much faster:

```
$ locate --existing -b --regex '.*idaq$'
```

**Comment by dbrumley** [comment]
One suggestion is to search the `$PATH` for `ida{q,l}`, and have an option to use `locate`, e.g., `--ida-locate`.  Right now `locate` is the default, which is nice for me but I could see why it's mysterious to others when it works without `ida` in the `$PATH`.

**Comment by ivg** [comment]
I just removed `locate` altogether, it is indeed very slow, even on some regular machines. Also, it tend to find wrong ida's, for example, for me it now always finds IDA free. So it will look at the path only.
Also, the correct way of solving this issue is to define ida location at configuration time. If a plugin is using some external tool, we should first package this tool as a special `<tool>-conf` package, and then rely on it. It is more correct to solve inter-program dependencies using package managers, native to the system.
