### ISSUE TITLE
Plugin deps and autorun

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#407]
If I run a simple plugin with the callsites dependencies like this:

```
open Core_kernel.Std
open Bap.Std
include Self()

let () =  Project.register_pass ~deps:["callsites"] (λ proj → proj)
```
it works:

```
00000137: sub main(main_argc, main_argv, main_result)
00000173: main_argc :: in u32 = R0
00000174: main_argv :: in out u32 = R1
00000175: main_result :: out u32 = R0
00000124: 
00000125: v47 := SP
00000126: mem := mem with [v47 - 0x4:32, el]:u32 <- LR
00000127: mem := mem with [v47 - 0x8:32, el]:u32 <- R11
00000128: SP := SP - 0x8:32
00000129: R11 := SP + 0x4:32
0000012a: SP := SP - 0x8:32
0000012b: R0 := 0xA:32
0000012c: LR := 0x8458:32
00000178: malloc_size := R0
0000012d: call @malloc with return %0000012e

0000012e: 
00000179: malloc_result := R0
0000012f: R3 := R0
```

Add the `~autorun:true` option, and callsites isn't working:
```
open Core_kernel.Std
open Bap.Std
include Self()

let () =  Project.register_pass ~deps:["callsites"] ~autorun:true (λ proj → proj)
```

```
00000137: sub main(main_argc, main_argv, main_result)
00000173: main_argc :: in u32 = R0
00000174: main_argv :: in out u32 = R1
00000175: main_result :: out u32 = R0
00000124: 
00000125: v47 := SP
00000126: mem := mem with [v47 - 0x4:32, el]:u32 <- LR
00000127: mem := mem with [v47 - 0x8:32, el]:u32 <- R11
00000128: SP := SP - 0x8:32
00000129: R11 := SP + 0x4:32
0000012a: SP := SP - 0x8:32
0000012b: R0 := 0xA:32
0000012c: LR := 0x8458:32
0000012d: call @malloc with return %0000012e

0000012e: 
0000012f: R3 := R0
```

Looks like `autorun` isn't being used in in `bap_project`, in fact: https://github.com/BinaryAnalysisPlatform/bap/blob/master/lib/bap/bap_project.ml#L292. Looks like setting `autorun` to true is triggering this line, without running deps: https://github.com/BinaryAnalysisPlatform/bap/blob/master/lib/bap/bap_project.ml#L276

But... I have no idea why this seems to work for `taint_main.ml`: https://github.com/BinaryAnalysisPlatform/bap/blob/master/plugins/taint/taint_main.ml#L116, I leave it to you to solve that mystery...

Tested with C program, compilation, and bap command line:

```c
#include <stdlib.h>

int main(void) {
  char * p = malloc(10);
}
```
`arm-linux-gnueabi-gcc -o test test.c`
`bap test --symbols=ida -lmain --main -dbir | less`

**Comment by ivg** [comment]
`callsites` is called, it just didn't find any arguments, so nothing is inserted. The autorun option is just a flag, that is used by a frontend, when it runs passes over the project, using `Project.run_pass` operation. From the perspective of `run_pass` function there is no difference between passes with autorun flag set on or off. It just runs a transitive closure of pass dependencies, and then the pass itself. A frontend can opt to treat autorun flag as he likes, he can even ignore it. The `bap` frontend, runs passes marked as `autorun` just after the project is created. So `taint` and your example without `autorun` works, because `api` plugin is run at `autorun` phase and they both get the project annotated with function parameters. When you're trying to run your pass in the autorun phase it works in the following order: `callsites -> main -> api`. There're only two plugins registered as `autorun`: `api` and yours `main`. Passes are run in a topological order, i.e., it is guaranteed that all pass dependencies are run before the pass. Since there is no dependency between `api` and `main` this is the possible valid topological sorting. The `callsites` pass has no dependency on `api`, since it is possible to have other ways to populate the project with arguments. Moreover, the project may even have arguments by default. Moreover, if there will be a dependency, then the `callsites` pass will not be callable if `api` plugin is not present. So, there is no good reason to add dependency between `callsites` and `api`. If you need to have `api -> callsites -> main` chain, then you can just say: `~deps:["api"; "callsites"]`, it is guaranteed, that dependencies are run in the specified order. But the general takeaway - don't abuse `autorun` option.
