### ISSUE TITLE
IDA loader option doesn't create segments?

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#440]
`bap /bin/true --loader=ida -lmain --main | less` is empty.
`bap /bin/true -lmain --main | less` has segments.

```ocaml
open Core_kernel.Std
open Bap.Std
include Self()
open Format

let print_segments p =
  Project.memory p |> Memmap.to_sequence |> Seq.iter ~f:(fun (mem,x) ->
      Option.iter (Value.get Image.segment x) ~f:(fun segment ->
          printf "Segment: %s@.%a@." (Image.Segment.name (segment)) Memory.pp mem))

let () = Project.register_pass' (fun proj ->
    print_segments proj)
```

**Comment by ivg** [comment]
yep, it doesn't, because IDA doesn't have segments in the ELF's sense. IDA's segments maps to ELF's sections :) As a workaround we can create a fake segment for each section (1-to-1 mapping). A more elaborated and (correct?) way, would be to merge contigious sections back into segments, based on whether they are code or data. But the latter doesn't guaranteeee a correct mapping to the real segments.

**Comment by dbrumley** [comment]
AFAIK, IDA plugins often merge in sections into one segment.  At least one plugin in the SDK does that (the source to many IDA loaders is in the SDK in case that wasn't known).

**Comment by ivg** [comment]
We can recreate segments by merging consequent sections with the same permissions. Putting this work into low priority queue.

**Comment by ivg** [comment]
No clear resolution, feel free to reopen, and propose a particular solution.
