### ISSUE TITLE
Default bap behavior changed

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#495]
BAP now seems to use byteweight first for a bunch of things and will give an opaque message: 

```
$ bap /bin/ls
Failed to create a project: no signatures
```

In the logs, it will instruct to run `bap-byteweight`. Correct me if I'm wrong, but the default behavior before was to use internal, until #484, I guess. The main problem here is that the default choice to union rooters, while also selecting uninitialized byteweight, means that the default `bap /bin/ls` is uninstructive about loading byteweight signatures and also doesn't do anything useful.

**Comment by ivg** [comment]
just use `opam` to install bap. It will install signatures for you.

**Comment by rvantonder** [comment]
I don't think that solution is good enough. For example, if I do `bap /bin/ls --symbols=ida`, it should set `--rooter=ida --symbolizer=ida`, and not even care that byteweight exists. But it does, and so if I run

`bap /bin/ls --symbols=ida` without byteweight signatures, I get
`Failed to create a project: no signatures`

**Comment by ivg** [comment]
Ok, here is the model, that we take. If a user says something, then we shouldn't be trying to be more clever, and decide, that a user actually wanted to say something else. If you loaded the `byteweight` plugin, then it means that you should use it. Otherwise why you installed it at all? The same with ida plugin, if it is loaded, then it should work. So do not install byteweight, or removed. If you installed it, then make sure, that you did it correctly. 

What concerning `symbols` option, I agree, it is counter intuitive. I think we should just remove it, as it actually doesn't make any sense to bring a connection between symbolizer and rooter. They are kind of orthogonal.

**Comment by ivg** [comment]
Since, you created a separate issue for the symbols, I will close this one. Feel free to reopen if you still any questions.
