### ISSUE TITLE
Iltrans

### ISSUE THREAD

**Issue by hxuhack** [BinaryAnalysisPlatform/bap#536]
Hi, I was using iltrans. Now, I cannot find the tool in the new repository. Is there any new model/command that substitute iltrans? Thanks!

**Comment by ivg** [comment]
Yes, it is called bap. Use --dump option, it accepts different formats, e.g., --dump=bil. Use --list-formats to get the full list of available formats, e.g., last adt is a more parseable representation of bil.

**Comment by hxuhack** [comment]
Thanks. I have tried several commands according to the manual but find they are really frustrating. Do you have handbook for the new version? 
My current need is to read pin traces in bpt format, lift them into BIL, and then extract the formula.

**Comment by hxuhack** [comment]
Hi, Ivan, Can you provide me some hints for this requirement? Thanks.
The requirement is to read pin traces in bpt format, lift them into BIL, and then extract the formula.

**Comment by hxuhack** [comment]
When I run 
        bap --trace-dump 86271-trace.frames. 

It outputs  "No provider for the given URI"
        Do I miss something?

**Comment by ivg** [comment]
Hi Hui, 

Sorry for the late replies, I'm on vacations, and my Internet access is very sloppy. You're on the right track, so far. Bap is able to work with traces. In order to get support for `frames` format you need to install corresponding plugin. It should be as easy as:

```
opam install bap-frames
```

As, it looks like that you already have everything else working. Also, if you have troubles in reading the trace, then make sure, that it is obtained from the latest version of [pintool][1] or [qemu][2]. There are comprehensive instructions in the README files of the repositories. 

Feel free to ask, if you have any questions.


[1]: https://github.com/BinaryAnalysisPlatform/bap-pintraces
[2]: https://github.com/BinaryAnalysisPlatform/qemu

**Comment by hxuhack** [comment]
Thanks for the feedback. I have two further questions. 

When I run 
bap --trace-dump 86271-trace.frames.  
It dumps the traces well;
However, when I run
bap --trace-dump=bil 86271-trace.frames.  the result is 
No provider for the given URI
Should I install other providers? Does bap have lifter in this version? 

The second question is: If I wanna integrate iltrans (lifter, and formula model) into current BAP architecture, what is your suggestion? I notice you have rewrite some component in C++ instead of OCaml, such as trace_container, right? Many thanks!

**Comment by ivg** [comment]
Command line option `--trace-dump` accepts a value that should be an URI of the trace. Two syntax of passing an option is accepted: `--trace-dump=<uri>` and `--trace-dump <uri>`. When you say, `bap --trace-dump 86271.trace.frames` it means "dump the trace from file  86271.trace.frames", when you say `--trace-dump=bil` it means dump the trace from file `bil`. 


> The second question is: If I wanna integrate iltrans (lifter, and formula model) into current BAP architecture, what is your suggestion?

Write a plugin that will use [traces](https://github.com/BinaryAnalysisPlatform/bap/blob/master/lib/bap_traces/bap_traces.mli) interface and will transform a trace into a formula.
