### ISSUE TITLE
support x86 `loop` instruction

### ISSUE THREAD

**Issue by occia** [BinaryAnalysisPlatform/bap#548]
I use the following code to test how bap handles assembly loop instruction.
```
int main()
  {
      asm(
          "movl $5, %ecx\n"
          "start_loop: \n"
          "loop start_loop \n"
      );  
   
      return 0;
  } 
```
and then compile it use gcc -m32.And I use bap to dump its bil format.
` bap ./a.out -d bil > loop.bil `
Finally,I got the following result in the main function part.
![image](https://cloud.githubusercontent.com/assets/14798217/18243489/d027dfee-738d-11e6-9ae3-f39819697677.png)
And here is the questions.
1. Why you design 'loop' as UNKNOWN SEMANTICS,as my point of view,translate 'loop' into BIL is not a hard thing.I haven't deep into your bap's disasm related source code,but I think it is not easy to manually fix it after the asm-to-bil phase. And this issue only affects static analysis.In dynamic analysis using Pin + pintrace,you've handled the REP PREFIX and Pin will record all runned iterations of loop automatically.Nothing should be done in 'loop'(perhaps this is why you treat 'loop' as UNKNOWN? If it is, is there a workaround in static analysis?).
3. Is there an full list of UNKNOWN SEMANTIC INSTRUCTION?
Any help is appreciated,thanks!

**Comment by ivg** [comment]
1. Indeed, there is nothing hard in expressing `loop` instruction semantics. And the complexity of instruction was never a critireum for us, when we chose what to lift and what not to lift. Today, when x86 instruction set consists of more than a thousand mnemonics (and the number of different instructions is even more) we need to prioritize on some instructions over another. The criterium that we used is very simple - we just counted all instructions on a regular machine and get the histogram of instruction distribution. Then we lifted most popular, so that when we disassemble a regular program compiled by gcc, we get 99.99% of instructions lifted. So it just happens, that gcc x86 backend doesn't know anything about the `loop` instructions and actually never emits it. 

2. ???

3. No, there is no such list (in fact it would be very hard to build such). Even a list of known instructions can't be generated for sure, as the lifter is not a static description file, but a program, that analyzes code and instruction. But we have a verification framework, that checks the output of the lifter, and verifies using dynamically generated traces. So that we can be sure, that the lifting was correct, and we understood a semantics of a program correctly.

**Comment by occia** [comment]
Sorry,the question 2 is :
      If I analyze some assembly that really contains the 0.01% instructions (e.g.loop),What is the recommended way to keep the consistency of the semantic,recognize the special insn and manually modify its lifted bils?

**Comment by ivg** [comment]
Well, ideally, would be to add this instruction to the lifter and contribute back :) Currently we're switching from the old legacy lifter to a new one, that is much easier to extend. I hope to finish the switch before the end of the week, so I can't right now give any instructions on how to do this (it may change few times per day). 

Of course, you don't need to change the bap code, and you can add new instruction dynamically (this is also a good way to test, that your lifting is correct). For this you can write a plugin, that will overload the default lifter and hijack this particular instructions.  Here comes the skeleton:

```ocaml
open Core_kernel.Std
open Bap.Std
open Bap_future.Std
open Bap_plugins.Std

open Disasm_expert.Basic

let main () =
  let module Super = (val target_of_arch `x86) in
  let module Target = struct
    include Super
    let lift mem insn = match Insn.name insn with
      | "LOOP" -> Ok [Bil.special "Known semantics"]
      | _ ->  Super.lift mem insn
  end in
  register_target `x86 (module Target)

let () = Future.upon Plugins.loaded main
```

Put this code into a separate folder into some ml file. Let's assume, that you named it `loop.ml`. Then you can compile and install it using:

```
bapbuild loop.plugin && bapbundle install loop.plugin
```

It is easier to test it using `bap-mc` frontend. Unlike `bap` it doesn't require the full binary, so you can feed small pieces of code into it, and lift them, e.g.,

```
$ bap-mc --show-bil --arch=x86 "\xe2\xfe"
{
  special (Known semantics)
}
```

So the next step, would be actually to add a correct semantics. But before this, let's do a small walk-through the existing code. 

```ocaml
open Core_kernel.Std
open Bap.Std
```

This is a usual start of any plugin. 

```ocaml
open Bap_future.Std
open Bap_plugins.Std
```

Our plugin is special, as it tries to hijack another plugin and overload it. This is not a usual way of doing things, as it is error prone and doesn't scale (what if someone else will try to do the same, or someone else will try to hijack our plugin ... that's why bap plugins are not doing such things). But it is ok for debugging and fast prototyping. The actual trick is the following code:

```ocaml
let () = Future.upon Plugins.loaded main
```

It literally says, as soon as all plugins are loaded, please call our function `main`. We need this, as the order in which plugins are loaded is unspecified. And it might be the case, that the `x86` plugins is loaded after us, so he will hijack us, instead of vice verse. So, to ensure, that the `main` function is evaluated after the main `x86` code, we are loading it after any other plugin. 


The code of the main function should be pretty obvious, but if it isn't then let me explain a little bit:

```ocaml
let main () =
  let module Super = (val target_of_arch `x86) in
  let module Target = struct
    include Super
    let lift mem insn = match Insn.name insn with
      | "LOOP" -> Ok [Bil.special "Known semantics"]
      | _ ->  Super.lift mem insn
  end in
  register_target `x86 (module Target)
```

For each architecture there is a module of type `Target` that implements its lifter (and few other things). First we obtain such module for the x86 architecture. And then we create a new module, with the `lift` function that is overloaded. It looks at the instruction opcode, and if it is our `LOOP` then we overload it, otherwise, we call to the super method.

So, why `LOOP`. The `Insn.name` is actually defined by the disassembler backend, and LLVM (our default disassembler), actually has its own way of representing assembly, called machine code, or MC. So, the easiest way to figure out how `llvm-mc` will disassemble it would be to use `bap-mc` (or alternatively the `llvm-mc`) 

```
bap-mc --show-insn --arch=x86 "\xe2\xfe"
LOOP(-0x2)
```

So, let's go to the next step, building a correct semantics. It should be easy, in comparison with the what we've already done.

```ocaml
module Loop = struct
  open X86_cpu.IA32

  let width = 32
  let zero = Word.zero width
  let one = Word.succ zero
  let two = Word.succ one

  let target = function
    | [| Op.Imm off |] ->
      Word.of_int64 ~width (Imm.to_int64 off)
    | _ -> failwith "Loop.semantics: expected one operand of type imm"

  let semantics pc ops =
    info "lifting loop";
    Ok Bil.[
      rcx := var rcx - int one;
      if_ (var rcx = int zero) [
        jmp @@ int pc + int two + int (target ops)
      ] []
    ]
end
```

The semantics itself is very simple. We need carefully extract the argument, and make sure, that we make our jump absolute. The rest is obvious, I think.  

So, the final code for the plugin is:

```ocaml
open Core_kernel.Std
open Bap.Std
open Bap_future.Std
open Bap_plugins.Std


open Disasm_expert.Basic

module Loop = struct
  open X86_cpu.IA32

  let width = 32
  let zero = Word.zero width
  let one = Word.succ zero
  let two = Word.succ one

  let target = function
    | [| Op.Imm off |] ->
      Word.of_int64 ~width (Imm.to_int64 off)
    | _ -> failwith "Loop.semantics: expected one operand of type imm"

  let semantics pc ops =
    Ok Bil.[
      rcx := var rcx - int one;
      if_ (var rcx = int zero) [
        jmp @@ int pc + int two + int (target ops)
      ] []
    ]
end

let main () =
  let module Super = (val target_of_arch `x86) in
  let module Target = struct
    include Super
    let lift mem insn = match Insn.name insn with
      | "LOOP" -> Loop.semantics (Memory.min_addr mem) (Insn.ops insn)
      | _ ->  Super.lift mem insn
  end in
  register_target `x86 (module Target)

let () = Future.upon Plugins.loaded main
```

Since, we are now depend on `bap-x86-cpu` library, that defines CPU descriptions for `x86`-family of processors, we need to update our building instructions:

```
bapbuild -package bap-x86-cpu loop.plugin && bapbundle install loop.plugin
```

Now we can run `bap-mc` and check that everything worked fine:

```
$ bap-mc --show-bil --arch=x86 "\xe2\xfe"
{
  ECX := ECX - 0x1:32
  if (ECX = 0x0:32) {
    jmp ((0x0:32 + 0x2:32) + 0xFFFFFFFE:32)
  }
}
```

So far, so good, now let's try the real application. First of all let's clean the caches, as bap will cache the disassembled file,

```
bap --cache-clean
```

And now let's take a look at the disassembled main function in the BIR representation:

```
bap a.out -dbir 
...
00000090: sub main(main_argc, main_argv, main_result)
000001f4: main_argc :: in u32 = mem32[ESP, el]:u32
000001f5: main_argv :: in out u32 = mem32[ESP + 0x4:32, el]:u32
000001f6: main_result :: out u32 = EAX
00000083: 
00000084: ESP := ESP - 0x4:32
00000085: mem32 := mem32 with [ESP, el]:u32 <- low:32[EBP]
00000086: EBP := low:32[ESP]
00000087: ECX := 0x5:32
00000088: ECX := ECX - 0x1:32
0000008a: EAX := 0x0:32
0000008b: EBP := mem32[ESP, el]:u32
0000008c: ESP := ESP + 0x4:32
0000008d: v29 := mem32[ESP, el]:u32
0000008e: ESP := ESP + 0x4:32
00000089: when ECX = 0x0:32 goto 0x80483F4:32
0000008f: return v29
```

So, now the bad news. Although it looks more or less fine, but loop instructions should be a separate basic block, and it is not. So we have some problem on the CFG reconstruction. Unfortunately, LLVM backend doesn't know the semantics of the `loop` instruction. It doesn't know that it is a barrier, or may affect control flow, etc. It is quite easy to fix it, by enforcing the disassembler to stop on each instruction and then check the instruction semantics by analyzing BIL. However this will have a severe impact on performance, and I'm not sure whether it is worthwhile given that the `loop` instruction is never used by compilers. Here is the correct disassembly, that I've obtained after the fix:

```

00000094: sub main(main_argc, main_argv, main_result)
000001f8: main_argc :: in u32 = mem32[ESP, el]:u32
000001f9: main_argv :: in out u32 = mem32[ESP + 0x4:32, el]:u32
000001fa: main_result :: out u32 = EAX
00000083: 
00000084: ESP := ESP - 0x4:32
00000085: mem32 := mem32 with [ESP, el]:u32 <- low:32[EBP]
00000086: EBP := low:32[ESP]
00000087: ECX := 0x5:32
00000088: goto %00000089

00000089: 
0000008a: ECX := ECX - 0x1:32
0000008b: when ECX = 0x0:32 goto %00000089
0000008c: goto %0000008d

0000008d: 
0000008e: EAX := 0x0:32
0000008f: EBP := mem32[ESP, el]:u32
00000090: ESP := ESP + 0x4:32
00000091: v291 := mem32[ESP, el]:u32
00000092: ESP := ESP + 0x4:32
00000093: return v291
```

**Comment by occia** [comment]
Thanks very much for your patience and your great tutorial :) It let me understand the solution totally.Thanks again~
