### ISSUE TITLE
bap-byteweight analysis questions

### ISSUE THREAD

**Issue by sborpo** [BinaryAnalysisPlatform/bap#554]
Hello,
After testing the bap-byteweight utility on few DLL's i have some questions:
1) Is the default installation of the bap-byteweight that comes with bap 1.0 alpha contains and updated trained data structure of signatures ?  when i tried to run `bap-byteweight update` it gave me this message:
`Program failed: failed to fetch : HTTP response code said error`
2) Is there an information about the function size , or the current implementation find only the entry points of the functions?
3) Is the byteweight algorithms based only on pattern matching ? or it uses some information inside the PE header directories for the analysis?
 I compared the analysis results with IDA on these DLLS and found some strange things, for example byteweight returned a function entry point inside another function that is on the export directory of the binary (It seems like it recognize the pattern and not using the information that it overlaps other function)
While Comparing it to kernel32.dll (version: 10.0.14393.0) symbol file - it seems like he missed the functions entries because a lot of them start with 
```
**mov esi, esi**
push ebp 
mov ebp, esp
```
so it had 0.002 accuracy comparing to the symbols.
Is something wrong with my configurations in byteweight ? how i can improve it?
Thanks a lot!

**Comment by ivg** [comment]
1. `bap-byteweight update` comes with the `--url` argument, with the default value that is calculated from the version. Each release contains the `sigs.zip` file with the signatures. Since `1.0.0~alpha` is actually a rolling release, that always points to the HEAD of the repo, it doesn't contain the signatures. As soon, as bap will be released, `bap-byteweight update` will work out of box, for now, you need to pass the url explicitly. If you will install from `opam` it will take care of obtaining the signatures for you, so you don't need to run `fetch` or `update`. Otherwise, you can take [the signatures][1] from the release 0.9.9, e.g.,
  ```
bap-byteweight update --url=https://github.com/BinaryAnalysisPlatform/bap/releases/download/v0.9.9/sigs.zip
```

2. Byteweight is only responsible for the entry points, the rest is done in the bap (using recursive descent disassembly). 

3. Byteweight is purely agnostic to metadata, and woks on a binary level. The bap itself, however, will look at the PE header and extract the information about symbols. 

As any machine learning algorithm, Byteweight will always depend on the choice of the training corpora. I'm not sure how you trained it, but if you didn't and used the signatures that are shipped with bap, then they won't perform well on windows shared libraries, because they were never trained on anything like this. The training corpora for them consists only from linux binaries from the coreutils suite, compiled with gcc. Ideally, we should train them on a much more representative set, that includes binaries from different platforms and different compiles. Presumably, we should also have different signatures for different compilers/ABI and choose one based on the deduced ABI of the input file (this is how it is done in IDA). The format of the signatures file, allows this (i.e., you can store several signatures in it).  See also #150.

[1]: https://github.com/BinaryAnalysisPlatform/bap/releases/download/v0.9.9/sigs.zip
