### ISSUE TITLE
How to obtain the LLVM code?

### ISSUE THREAD

**Issue by frala19871987** [BinaryAnalysisPlatform/bap#574]
Hi,
is it possible to obtain the LLVM starting from the assembly code? I'd like to have any LLVM instruction represented a Python object that I can use.

My goal is just to have a platform agnostic representation of the assembly code. Do you think BIL would be better?

Thanks for your help

**Comment by ivg** [comment]
If you're talking about LLVM IR, then it is not possible right now. However, it would be easy to write a `BAP IR -> LLVM-IR` transformation. Unfortunately, I don't have time right now, to implement it myself, but I will create a feature request, in a hope, that someone will implement it. 

> My goal is just to have a platform agnostic representation of the assembly code. Do you think BIL would be better?

Yep, I think that BIL is better, as it was designed for this specific purpose. The BAP IR, that is an intermediate representation of BIL, is actually very close LLVM IR, that's why I'm claiming that it would be easy to write a transformation from one to another. Another good point of the BIL is that it is formally specified and is mostly side-effect free, that facilitates writing formal program analysis tools.

**Comment by ivg** [comment]
Issue #575 is created. 

P.S. although I closed the issue, under assumption that I provided a full answer to your question,  don't hesitate to ask more questions or to reopen the issue again, if my assumption was wrong :)

**Comment by frala19871987** [comment]
Hi,
no worries I didn't close the issue on my own because i wasn't at home.

You clarified my doubts.

Thanks
