### ISSUE TITLE
Symbol doesn't fit into memory

### ISSUE THREAD

**Issue by windflyer** [BinaryAnalysisPlatform/bap#580]
I tested bap with this ARM32 binary: [ `mtpd` ](https://github.com/BinaryAnalysisPlatform/bap/files/530160/mtpd.zip)

(click to download, compressed because github doesn't allow attaching an ELF)
 
I got the following error:

```
$ bap mtpd -d
Aborting because (("symbol at" ((z 0x0) (w 32) (signed false))) ("with size" 0)
 ("doesn't fit into memory"
  (((z 0x0) (w 32) (signed false)) ((z 0x57E9) (w 32) (signed false))))
 ("validation errors"
  (("preconditions.size fits" "value 4294967296 > bound 22506")
   ("preconditions.size fits" "value 4294967296 > bound 22506")))).
```

**Comment by ivg** [comment]
Can't reproduce it:
```
d$ bap mtpd -d | wc --lines
1299
```

Probably you're using some old version of bap. Please, install `bap.1.0.0`.

**Comment by windflyer** [comment]
Thanks for your prompt response. I followed installation instructions in README. The version I installed is 0.9.8. I'll try 1.0.0.

**Comment by ivg** [comment]
Yeah, it sometimes happens when you have some packages already installed in a switch, then opam may decide, that is easier to install some old version of BAP instead of upgrading/reinstalling all other packages. See also: https://github.com/BinaryAnalysisPlatform/bap/wiki/Troubleshooting-installation

**Comment by windflyer** [comment]
1.0.0 works perfectly. Thanks a lot :)
