### ISSUE TITLE
`bap-byteweight` in help but may not be installed

### ISSUE THREAD

**Issue by dbrumley** [BinaryAnalysisPlatform/bap#584]
The `bap` documentation mentions `bap-byteweight` at:
https://github.com/BinaryAnalysisPlatform/bap/blob/master/src/bap_main.ml#L194

I think to get this you need to install `bap-byteweight-frontend`, which may not be installed.

**Comment by ivg** [comment]
There are all packages in the help, but not all packages are installed, to prevent the dependency hell. Do `opam install bap-byteweight-frontend` if you need it.

**Comment by ivg** [comment]
btw, it is noted in the documentation.

**Comment by dbrumley** [comment]
> btw, it is noted in the documentation.
I don't get what you are saying. Maybe I'm not clear either.

```
$ bap --help
...
SEE ALSO
       bap-mc(1), bap-byteweight(1), bap(3)
```
Is it clear to everyone else that you should install l `bap-byteweight-frontend` (the opam package) to get the `bap-byteweight` (binary)?  I'm suggesting it might be confusing to reference a command that doesn't correspond to an opam package in this case since there is an opam package with the same name, but is not the command.

**Comment by ivg** [comment]
So? What are suggestions? I can remove the reference all together? Or I can install the bap-byteweightfrontend that is not needed by 99% of users, but will bring tons of dependencies, or I can just drop the reference from the documentation, so that no one will ever know that such a frontend exists at all. Btw, it is common for linux man-pages, to have a references to the packages that are not installed.

**Comment by dbrumley** [comment]
Hmm.  The problem is a name clash between two types of things: a package and a command line meaning different things.  My suggestion would be to differentiate the names.

For example, call the command line tool `bap-ibyteweight` (python-ism for interactive?) or just rename the line `bap-byteweight-frontend` keeping the package name for it the same.

**Comment by ivg** [comment]
There is no name clash, there is a library `bap-byteweight(3)` and a command line utility `bap-byteweight(1)`.

**Comment by dbrumley** [comment]
the `bap-byteweight(1)` command line is installed by `bap-byteweight-frontend`, and the `bap-byteweight(3)`  is installed by `bap-byteweight`.   that's a 1->2 mapping if you remove the parens.

**Comment by ivg** [comment]
Yep, it is not that hard to do `opam search bap-byteweight` to get the both results, and install the required package. I can't name the library package and the frontend the same. I do not see any sense in adding `frontend` suffix to the command line utility. All command line utilities are frontends, so it is the same as saying `ls-binary` to me. And of course, the man page should correspond to the actual name of the binary, not to the name of a package in the opam repository, especially, since opam is just one of the package managers. For example, if we will release to ubuntu, we will need to name it as `ocaml-bap-byteweight-frontend`, should we also rename it, to match with the package management naming convention?

**Comment by maurer** [comment]
@ivg What about noting what opam packages are needed for each binary in the manpages, but installing all manpages with the base package? It's not ideal, but it'll allow you to have a no-actual-dependencies main package which tells you how to use all the other ones.

**Comment by ivg** [comment]
@maurer, first of all opam is just _a_ package manager so and I'm trying not to rely on it. Second... well, bap is not a linux distribution, it is so easy to do `opam search bap` and too look on a very small set of available tools :) Third, it is actually mentioned in the documentation, that not all packages are installed by default, and if you want more, then use `opam` or `whatever-package-manager` are you using.
