### ISSUE TITLE
Project fails to load due to lifter error when loading binaries built by gcc 5.4

### ISSUE THREAD

**Issue by maurer** [BinaryAnalysisPlatform/bap#642]
[dummy](https://data.maurer.codes/dummy) [dummy.c](https://data.maurer.codes/dummy.c)

```
[maurer@durandal:~]$ bap ~/dummy
Failed to create a project: Option.value_exn None

[maurer@durandal:~]$ bap ~/dummy --x86-lifter=legacy

[maurer@durandal:~]$ 
```

A simplified version of this issue, depending only on `bap-mc`:
```
[maurer@durandal:~]$ echo "8b 04 25 00 00 00 00 0f 0b" | bap-mc --show-size --show-insn --x86-lifter=modern
0x7
MOV32rm(EAX,Nil,0x1,Nil,0x0,Nil)
Uncaught exception:
  
  "Option.value_exn None"

Raised by primitive operation at file "src/option.ml", line 59, characters 4-21
Called from file "plugins/x86/x86_mov.ml", line 38, characters 12-44
Called from file "src/bap_mc.ml", line 78, characters 10-23
Called from file "src/bap_mc.ml", line 89, characters 14-39
Called from file "src/bap_mc.ml", line 100, characters 4-34
Called from file "src/bap_mc.ml", line 118, characters 16-35
Called from file "lib/bap_disasm/bap_disasm_basic.ml", line 519, characters 2-32
Called from file "lib/bap_disasm/bap_disasm_basic.ml", line 510, characters 2-7
Called from file "src/bap_mc.ml", line 262, characters 22-50

echo "8b 04 25 00 00 00 00 0f 0b" | bap-mc --show-size --show-insn --x86-lifter=legacy
0x7
MOV32rm(EAX,Nil,0x1,Nil,0x0,Nil)
0x2
TRAP()

[maurer@durandal:~]$ echo "0f 0b" | bap-mc --show-size --show-insn
0x2
TRAP()

[maurer@durandal:~]$ 
```

`gcc` 5.4 generates `0f 0b` in some cases, and currently this will prevent the binary from loading (not just stop semantics from being generated).

**Comment by ivg** [comment]
@maurer,  the mc example is actually broken. Notice, that in the first call to `mc` we are passing the `--x86-lifter=modern`, while in the second it is `--x86-lifter=legacy`. If you will remove this option from the second example, it will fail as expected, with or without the following ud2 instruction. 

The root of the problem was the move operation, that had a zero displacement (basically a read from the NULL address), that, for some reason was considered as impossible by the lifter author.
