### ISSUE TITLE
Bap not compatible with utop 2.x

### ISSUE THREAD

**Issue by RabidCicada** [BinaryAnalysisPlatform/bap#674]
I kept getting Undefined Reference to Longident error when trying to run baptop.  It turned out to be related to a new incompatibility with utop 2.x due to them defining compiler-libs as a dependency.  I believe it's related to:
https://discuss.ocaml.org/t/ppx-tools-not-working-in-utop/367/2

Opam install utop=1.19.3 solved the problem.
utop 2.0.1 and up causes me problems (And I assume others)

**Comment by ivg** [comment]
Thanks for reporting and for doing the research. On the first glance it looks like that we either need to wait until the compiler libs adopt a more sane naming convention or until the namespaces are added to the compiler. Don't except either of the events to happen in the next year, probably, we should wait until 4.07+. 

Until then, we can just constraint the version number (not sure where, as bap formally don't have any dependencies on utop), or use utop-full in the baptop. I will investigate other options though, maybe there is an alternative solution. 

Since compiler-libs are also expunged from the standard top-level, I would expect bap (as well as all other ppx-dependent libraries, e.g., janestreet core, etc) to be broken in the standard toplevels (starting from some version). 

Linking the relevant diml/utop#213 for tracking the issue.

**Comment by XVilka** [comment]
Ah, I met the same. Just used utop-full.

**Comment by RabidCicada** [comment]
For someone Brand spankin new to ocaml/opam/bap...and trying to run on ubuntu16.04 with llvm3.8...this was very hard too figure out:).  Common sense now:).

**Comment by RabidCicada** [comment]
Also...when I run the following I get the following output:
#require "bap.top";;
The files /tmp/trace52ed50.cma                                                                                                                                                    and /home/dev/.opam/4.02.3/bin/utop-full                                                                                                                                          disagree over interface Trace

**Comment by ivg** [comment]
This is a name clash between the `trace` plugin in BAP and `trace` library linked and exposed in the `utop-full`. We will try to mangle our plugin names to minimize further conflicts, meantime, a workaround would be to disable `bap-trace` plugin with 

     opam remove bap-trace

**Comment by dbrumley** [comment]
FWIW, `utop-full` takes seconds to load on my macbook pro, while `utop` loads much more quickly.  Don't know if everyone has that behavior, and not sure what is causing it. The reason I mention is `utop-full` wouldn't provide an acceptable user experience as-is.

**Comment by XVilka** [comment]
Just FYI, seems like utop < 2.0 have problem with Core libs https://github.com/janestreet/core/issues/85#issuecomment-304251993

**Comment by XVilka** [comment]
So far there is no short-coming solution for this problem, until OCaml will introduce namespaces and they will be integrated across libraries, which can take years.

**Comment by ivg** [comment]
we solved it so far by constraining the upper bound of the utop version in the opam repository. We will eventually provide a more reliable fix, like implementing our own `baptop` using utop as a library.
