### ISSUE TITLE
Expanding on the Jmp.plugin example

### ISSUE THREAD

**Issue by Dinatrix** [BinaryAnalysisPlatform/bap#689]
Hello,

I was trying to expand upon the jmp.plugin example (shown here: https://github.com/BinaryAnalysisPlatform/bap). 

I was testing this plugin against a simple test program compiled from C code:

#include <stdio.h>

int main(){
        int i;
        for (i=0; i < 2; i++){
        /*bap jmp plugin output, jmps = 52, total = 529*/
        }
        for (i=0; i < 2; i++){
        /*adding this loop, bap jmp plugin output, jmps = 54, total = 552*/
        }
        for (i=0; i < 4; i++){
        /*adding this loop, bap jmp plugin output, jmps = 60, total = 575*/
        }
        return 0;
}

I kept adding loops and checking the jmp.plugin output, but the numbers didn't seem correct. (ex. why would a loop with i < 2 have the same number of jumps as one with i < 4)

Curious to see when the jmp and total variables are incremented, I tried putting some printf statements into the jmp.ml file:

open Core_kernel.Std
open Bap.Std

let counter = object
            inherit [int * int] Term.visitor
            method! enter_term _ _ (jmps, total) = jmps, total+1
            printf "check 1 jumps %d" jmps
            method! enter_jmp _ (jmps, total) = jmps+1, total
            printf "check 2 jumps %d" jmps
end

let main proj = 
            let jmps, total = counter#run (Project.program proj) (0,0) in
            printf "ratio = %d/%d = %g\n" jmps total (float jmps /. float total)

let () = Project.register_pass' main

But ran into an error when running bapbuild:
File "jmp.ml", line 7, characters 50-51:
Error: This expression has type int
          This is not a function; it cannot be applied.
Command exited with code 2.

It seems to be including the printf as part of the previous method line? I tried separating the lines with ;; but saw a syntax error. Is it not allowed to use a printf after that method line? Is there a way to see how/when the jmp value is updated with a print statement elsewhere in this program?

Thanks for taking a look at it!

**Comment by ivg** [comment]
First of all about the number of jumps. The plugin doesn't count the number of times a jump instruction is called, but the number of branch instructions in a program. In other terms, this is a total number of edges in an control flow graph. 

Concering the OCaml code, the body of a method should be an expression, that computes a value of a type, that is expected by this method signature. In our case, it should be a pair of integers. Your expression is `jmps, total+1 printf "check 1 jumps %d" jmps` that is parse by a compiler as ``jmps, total+(1 printf "check 1 jumps %d" jmps)` so it tries to call function `1` with the `printf "check 1 jumps %d" jmps`, since `1` is definitely not a function, it is an error. This is how it should be done:
```ocaml
method! enter_term _ _ (jmps, total) = 
   printf "check 1 jumps %d" jmps; 
   jmps, total+1
```

**Comment by ivg** [comment]
feel free to reopen, or open a new one if you have a question. Also you may ask question in our [gitter][1] chat.

[1]: https://gitter.im/BinaryAnalysisPlatform/bap

**Comment by wonderluster** [comment]
I need to get the instruction number of **conditional** jump (branch) and function call, how to write it in Python?  I'm not familiar with OCaml.
