### ISSUE TITLE
conf-bap-llvm.1.1 breaks depext on debian

### ISSUE THREAD

**Issue by percontation** [BinaryAnalysisPlatform/bap#716]
llvm-3.4-dev no longer exists on strerch, making depext fail.

(conf-bap-llvm.1.0 just specified llvm-dev, so that previously worked.)

Maybe there's some "llvm-%{conf-llvm}%-dev" thing that would work here?

**Comment by ivg** [comment]
Most likely it will break Jessie. The problem is that we can't parametrize depext dependencies with the distributive version. The depexts are parsed by the depext plugin, before any resolutions are made without giving us a chance to do anything. Basically, the system is broken. But in any case, you can always install the dependencies manually, and then just proceed to the `opam install bap` and it will care of the opam part.

**Comment by percontation** [comment]
Oh well. Yeah, not a big deal, the opam install still works fine. Maybe one day someone can add an applicable depext feature.
