### ISSUE TITLE
`bap depext --install conf-llvm=3.8 bap` still tries to install llvm-3.4

### ISSUE THREAD

**Issue by dbrumley** [BinaryAnalysisPlatform/bap#731]
Subject says it all.  Log of output shows `llvm-3.4-dev` trying to be installed in addition to `llvm-3.8-dev`.  This will prevent a user from installing using the BAP README.md, but it's also a trivial thing to fix.

Output from my debian box:
```
$ opam depext --install conf-llvm=3.8 bap
# Detecting depexts using flags: x86_64 linux debian
# The following system packages are needed:
#  - binutils-multiarch
#  - clang
#  - debianutils
#  - libgmp-dev
#  - llvm-3.4-dev
#  - llvm-3.8-dev
#  - m4
#  - ncurses-dev
#  - perl
#  - pkg-config
#  - zlib1g-dev
# The following new OS packages need to be installed: binutils-multiarch clang libgmp-dev llvm-3.4-dev llvm-3.8-dev
The following command needs to be run through "sudo":
    apt-get install binutils-multiarch clang libgmp-dev llvm-3.4-dev llvm-3.8-dev
```

This fails since my debian only has llvm-3.8-dev.

To anyone reading this: it's trivial to fix, and not likely a high priority to fix.  Run the command as described in the readme,  cut-and-paste the apt-get and remove `llvm-3.4-dev`, and then re-run.

```
$ sudo apt-get install binutils-multiarch clang libgmp-dev llvm-3.8-dev
$ opam install conf-llvm=3.8 bap
```

**Comment by ivg** [comment]
This is a known issue, that originates from tools that we do not control. We are slowly moving away from depending on them. As of bap.1.3 we no longer use or respect the `conf-llvm` package. We are going to stop using the depext plugin for handling external dependencies, as it is not flexible enough to handle our dependency constraints (that are very simple actually). Since we do not control opam or opam depext, we will soon move to a simple installation script, that will install (probably interactively) all the required external dependencies based on the auto-detected user OS.  

Since we are no longer respecting the conf-llvm package as a source of  the llvm-version, starting from the 1.3 release a user should specify the LLVM_CONFIG variable in the environment to choose a particular installation of LLVM. This is not required unless a user has several installations, and wants to choose a particular one. So in your case, opam will pick the right version without any variables. We do not provide the corresponding `depext` functionality, so if by default `depext` doesn't magically choose the right version of llvm, then the only solution is to install external dependencies manually. 

I will update the documentation (README and wiki) to reflect this, and we will soon add the installation script, that will handle the external dependencies.
