### ISSUE TITLE
build error: Error: Unbound module BaseEnv

### ISSUE THREAD

**Issue by vanhauser-thc** [BinaryAnalysisPlatform/bap#738]
I am on Kali Linux and tried to install bap.
All dependencies are installed, I did opam init ; opam config env ; opam config setup -a
and oasis is installed as well, first as package but since the Internet suggested it is part of oasis I also did "opam install oasis" as well.

still I get:

$ make
ocaml setup.ml -quiet -build 
File "oasis/common.setup.ml.in", line 5, characters 21-39:
Error: Unbound module BaseEnv
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

what am I missing?

**Comment by ivg** [comment]
First of all, did you try to install using OPAM with the simple `opam install bap`? Because, building BAP from sources is only required if you're going to change the BAP source code. If you need to use BAP, you don't need the source code. You can extend BAP using the plugin system. So building from sources is discouraged, unless you really know what you want. 

But if you still want to build from the sources, then should follow the general `./configure && make && make install` recipe. 

The `configure` script will setup the build system, you need to specify which component are you going to build, if you want to build everything you can use the `--enable-everything` flag. Usually, I'm invoking it usually as follows:
```
./configure --enable-everything --prefix=`opam config var prefix`
```

Or, when I'm working with one specific component:

```
./configure --enable-monads
```

There are many configuration options, look at the `./configure --help` for the detailed description.

The configure script will fail if there are missing dependencies, by default we prune error messages, since OASIS, the underlying mechanism of our building system, is too verbose and outputs lots of false positives. If your configure script failed (returned a non-zero error code), then you may want to look at the more detailed output, by enabling the debugging, e.g.,

```
BAP_DEBUG=1 ./configure <other-options>
```

Once you managed to satisfy all the needs of the configure script you can run `make` and then `make install` or `make reinstall`.

**Comment by XVilka** [comment]
Interesting, that I started to get this error too.
If I do `BAP_DEBUG=1 ./configure --enable-everything --disable-ida --disable-fsi-benchmark --prefix=\`opam config var prefix\`` it returns an error:
```
E: file "_oasis", line 153, characters 0-1: mixed use of '\t' and ' ' to indent
```
Without BAP_DEBUG configure runs, but make returns the error of unbound BaseEnv module.

**Comment by ivg** [comment]
Interesting, can you show the generated _oasis file?  Also, what version of oasis are you using?

**Comment by XVilka** [comment]
oasis version 0.4.7, opam version 2.0.0~beta6, ocaml 4.05.0 on Fedora 27 x86_64. It seems problem was with tabs in _oasis for my MIPS plugin. After that problem disappeared.
