### ISSUE TITLE
plugin load error

### ISSUE THREAD

**Issue by huangshiyou** [BinaryAnalysisPlatform/bap#741]
I just wanna test the plugin in the README. I build and install the plugin as required. But it gives the following error:

bap ./a.out --pass=jmp
loader.error> Failed to load plugin "jmp": a name "check_path" clashes with a plugin bir-to-llvm
Failed to find pass: jmp

I installed bir-to-llvm plugin before, but it returned the similar error. I checked the plugins by --list-plugins. Both of jmp and bir-to-llvm are listed.

**Comment by ivg** [comment]
Each plugin should be built in a separate folder. It looks like, that you built them from the same folder and they both have a `check_path.ml` file, that was linked with both of them, and now they are conflicting. When you're doing `bapbuild <plugin>.ml` it assumes, that all files in the folder belong to the plugin.

**Comment by huangshiyou** [comment]
Thanks @ivg 
I have one silly question. BAP has provided some plugins.
 [+] abi                        apply abi information to a project
  [+] api                        add parameters to subroutines based on known API
  [+] arm                        provide ARM lifter
  [+] beagle                     microx powered obfuscated string solver
  [+] bir-to-llvm                description not provided
  [+] byteweight                 find function starts using Byteweight algorithm
  [+] cache                      provide caching services
  [+] callsites                  annotate callsites with subroutine's arguments
  [+] cxxfilt                    provide c++filt based demangler
  [+] dead-code-elimination      automatically removes dead code
  [+] demangle                   demangle subroutine names
  [+] dump-symbols               dump symbol information as a list of blocks
  [+] frontc-parser              parse c files with FrontC
  [+] llvm                       provide loader and disassembler using LLVM library

When I use --pass=PLUGIN to use them, why does it report, 
"FAILED to find the pass". Do I use the plugins in a wrong way?

**Comment by ivg** [comment]
Not all plugins are passes. Plugins are loaded automatically and provide different facilities. Some of them provide passes, i.e., program transformations. These transformations could be invoked using the `--pass` option. To get the list of plugins that provide passes, use the following command:

```
bap  --list-plugins=pass
```

P.S. sorry for the late reply, the notification system on GitHub is strange, so I usually see only the first message. In case if we do not reply timely, feel free to create a new issue, contact us via [gitter][1], or ask a question on https://discuss.ocaml.org and tag it with `bap`. 

[1]: https://gitter.im/BinaryAnalysisPlatform/bap

**Comment by benben2301** [comment]
Hi, I try to use the build-in plugins, but some of the plugins cannot be found:

$ bap --list-plugins=pass
  [+] abi                        apply abi information to a project
  [+] api                        add parameters to subroutines based on known API
  [+] beagle                     microx powered obfuscated string solver
  [+] byteweight                 find function starts using Byteweight algorithm
  [+] callsites                  annotate callsites with subroutine's arguments
  [+] dead-code-elimination      automatically removes dead code
  [+] map-terms                  map terms using BML DSL
  [+] primus-propagate-taint     a compatibility layer between different taint analysis frameworks
  [+] primus-taint               a taint analysis control interface
  [+] propagate-taint            propagate taints through a program
  [+] run                        a pass that will run a program
  [+] ssa                        translates a program into the SSA form
  [+] strings                    find strings of characters
  [+] taint                      taint specified terms
  [+] trace                      manage execution traces
  [+] trivial-condition-form     eliminates complex conditionals in branches

When I try to run "bap ~/test/test --pass=primus-propagate-taint",  "bap ~/test/test --pass=primus-taint", "bap ~/test/test --pass=taint",  "bap ~/test/test --pass=trace", it gives the error info : Failed to find pass: xxxxx. 

Should I give the correct arguments to the pass, otherwise, I will get this error?
