### ISSUE TITLE
how to debug the bap plugin?

### ISSUE THREAD

**Issue by CAFA1** [BinaryAnalysisPlatform/bap#753]
How to debug the bap plugin with the vs code?

**Comment by ivg** [comment]
OCaml works pretty well with GDB and if VS Code integrates with GDB it should work. Since the code of a plugin is bundled as a shared library you need to instruct the loader to keep the shared code available, so that GDB could load the library debugging symbols. This is controlled via the `BAP_DEBUG` environment variable, set it to some value that is not zero, e.g., `export BAP_DEBUG=1`.

**Comment by ivg** [comment]
feel free to reopen, if the issue is not resolved
