### ISSUE TITLE
Why and how to use BAP with IDA Pro?

### ISSUE THREAD

**Issue by meteorlxy** [BinaryAnalysisPlatform/bap#783]
I'm new to BAP, and I couldn't find the answer of some questions in the docs.

1. I notice that BAP can perform disassembling itself, so in which situation do we need IDA Pro? Can BAP use the data in the `.idb` files so that BAP doesn't need to disassemble the program again?
2. I may want to use IDA Pro and BAP together, is there some demo code?

Thanks a lot.

**Comment by ivg** [comment]
> I notice that BAP can perform disassembling itself, so in which situation do we need IDA Pro?

BAP is a platform and we believe that we can achieve best results by using all available tools in the industry instead of competing with them. So far we have only IDA Pro integration, but we plan to extend it in future to radare2, angr, binary ninja, etc. If IDA Pro is installed and the `bap-ida` integration package is installed IDA will be used automatically to obtain symbol name information and entry points locations. We abstract those two integration points with the symbolizer and rooter services. 

> Can BAP use the data in the .idb files so that BAP doesn't need to disassemble the program again?

No, we do not really use the disassembly of IDA Pro per se. Though BAP will not disassemble program again, as we use caching infrastructure, that will store the disassembly. However, if there is an IDB file in the folder where you run bap, it will be used, so if you added any new symbols or renamed existing, you will see the same picture in BAP. The same is true if you're using BAP from IDA (not from a console) all symbols and even types information is propagated to BAP. 

> I may want to use IDA Pro and BAP together, is there some demo code?
Yep. https://github.com/BinaryAnalysisPlatform/bap-ida-python

Besides, I would like to note, that our IDA Pro integration is two-way, we can use IDA to provide services for BAP and vice verse. In the demo the latter part is shown. (The former part doesn't need any demo, as it happens without any user interaction, other than installing the `bap-ida` package with `opam install bap-ida`).
