### ISSUE TITLE
Does BAP support VSA

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [BinaryAnalysisPlatform/bap#903]
Hi guys. I am purely new to BAP.

Right now, I tried to do some binary-level data dependency analysis. From this [paper](http://users.ece.cmu.edu/~aavgerin/papers/bap-cav-11.pdf), it indicates that BAP have similar functionality. But after searching the codebase, I failed to find such code.

I must miss something. So may I ask whether BAP offers any VSA or data dependency analysis for machine code? Thx you guys.

**Comment by ivg** [comment]
The paper that you're referencing is very outdated and talks about the old version of BAP. The current BAP (as of 1.5) has VSA, it is developed by the Draper Laboratory and uses modern, state of the art techniques.  It is a work in progress, but it was already pre-released via the 1.5 version, so that you can play with it. You can also read the source code [here][1]. 

Besides VSA we have a dependency analysis in form of a taint analysis that uses a microexecution technology called Primus, underneath the hood. Roughly, it executes (emulates) the lifted version of the binary while observing the data dependencies. Primus enables user customizations for specifying your own policies both for data propagation and security specifications. 

[1]: https://github.com/draperlaboratory/cbat_tools
