### ISSUE TITLE
Optimizing

### ISSUE THREAD

**Issue by kozera2137** [BinaryAnalysisPlatform/bap#904]
Hi. It's my first contact with BAP and OCaml. I'm searching for a way to simplify some obfuscated assembly, it contains a lot of useless code like double assigments or CMC CLC CMC. However I cannot figure out how to use optimizations.
So my questions is how to run it? I have tried it
bap ../Desktop/sample.out -p dead-code-elimination -d
but it still generates lot of bullshit like this
```
00000007: RBX := 0x14
00000008: RBX := 0x1E
```
Could you please give me example how to use it?

**Comment by kozera2137** [comment]
@ivg I have checked and I have 1.4.0 version installed. As far as I can see version 1.5.0 is available on opam, however when I'm trying to upgrade it using opam, or by installing newest docker container still getting 1.4 version. I'm using Ubuntu 16.04.5 LTS and opam/xenial,now 1.2.2-4 amd64 [installed]. Where is the problem?

**Comment by ivg** [comment]
Nope, there are no problems. You might be using the old version of `opam`, e.g. 1.x, in order to get the lates 1.5 opam you need to upgrade it to 2.x, which is required by OPAM repository since September. You can also use debian packages. 
```
wget https://github.com/BinaryAnalysisPlatform/bap/releases/download/v1.5.0/{bap,libbap,libbap-dev}_1.5.0.deb
sudo dpkg -i {bap,libbap,libbap-dev}_1.5.0.deb
```

Also, if you have successfully installed bap from opam, but still don't see it make sure that you have activated your opam switch, by doing the following command before you're running bap:
```
eval $(opam config env)
```

**Comment by kozera2137** [comment]
Thanks for help. Upgrading opam helped, however optimizations aren't powerful enough to even get rid of this double assignment.

**Comment by ivg** [comment]
Did you specify the  `--optimization-level=3`?
