### ISSUE TITLE
clang-7: unknown argument: '-fstack-clash-protection'

### ISSUE THREAD

**Issue by XVilka** [BinaryAnalysisPlatform/bap#918]
Installing BAP from git on Fedora 29
```
Clang version: 7.0.1 (Fedora 7.0.1-1.fc29)
```
![screenshot_20190201_154136](https://user-images.githubusercontent.com/203261/52109282-eba49780-2637-11e9-8348-62b2434d34fc.png)
Sorry for the screenshot, but something happened with my clipboard application, crashed or something

**Comment by ivg** [comment]
Those options come from `llvm-config`, so we don't control them. In other words in means that LLVM of whatever version you're using is not buildable under Clang 7.0.1. Maybe you can try an newer version of LLVM? Otherwise, if it is the newest, we should probably go to the upstream.

**Comment by XVilka** [comment]
Yes, it is returned in `llvm-config --cxxflags` output, and 7.0.1 is the latest version.

**Comment by ivg** [comment]
So it looks like that `llvm-config` produces this option for `gcc` so it doesn't work with clang (apparently they don't support their own compiler :D) 

Anyway, historically we were building with clang++ because at that times the C++11 standard wasn't well adopted, and there were many compilers in the wild that either didn't support it, or supported it with bugs. So we decided to switch on clang++ as the default compiler since it was the most conforming compiler of the time. Mostly, this was to support old Mac OS X versions, like Maverick and older. As of today, I believe, we can switch to gcc as default, or, in fact, just use the default `g++` on the system, and hope that it will work. 

@gitoleg, could you please drop the `with-cxx=$(which clang++)` stanza from our configuration?

**Comment by gitoleg** [comment]
Turned out that using a system `c++` didn't make us happy. Tests on `travis` failed with the next error:
`unrecognized command line option  -Wstring-conversion`. And it's only one particular case, I can't even imagine how many similar errors we can expect.
As a result, we can't drop `clang` dependency so easy since builds with `clang` are less fragile then builds with system `c++`. 
Feel free to reopen this issue, if you have some ideas, questions, etc.
