### ISSUE TITLE
Wiki update for developing against bap

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#96]
For a bap developer setup (built from github), it is easier to install the right dependencies by doing:

```bash
$ opam install bap --deps-only
```

The reasoning here is that, if you are interested in developing specifically against bap , this will install the exact dependencies it is built on, so you don't have to worry about `opam upgrade`. It can replace the following on the wiki:

# Installing OCaml dependencies

The easiest way to install the OCaml dependencies of `bap` is to use
the `opam` package manager:

```bash
$ opam install $(cat opam.deps)
```

If you are using a development version, e.g., you have just cloned this from
github, then you will also need the `oasis` package in order to create a build
environment.

```bash
$ opam install oasis
```

**Comment by ivg** [comment]
I'm totally agree, you can fix the wiki. But since you've created an issue, I would also add, that we should totally remove this `opam.deps` because it violates SPOT rule, we have our dependencies specified in three places: `opam.deps`, `opam` at `bap` repository and `opam` in `opam-repository`. So we should use this `opam install --deps-only bap` trick in our CI script to install dependencies.

**Comment by rvantonder** [comment]
787bc97
